import {runQueueItems,itemCaptureFailure} from './queue-failure-policy.mjs';
import {MAX_SCREENS,TARGET_PRODUCTS,captureProgress} from './capture-budget.mjs';
import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';const require=createRequire(new URL('../../runtime/package.json',import.meta.url)),sharp=require('sharp');
const root=path.resolve(import.meta.dirname,'../../local-test/auto-search-trial');fs.mkdirSync(root,{recursive:true});const profile='3059CDF2-1184-45B6-9938-A3E990EBCBE9',vmBase='http://127.0.0.1:35000/api/v1/profile',base='http://127.0.0.1:37822';
const queue=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));if(!Array.isArray(queue)||queue.length<1||queue.length>20)throw Error('Queue must contain 1-20 anchors');const report={profile,started:new Date().toISOString(),maxScreens:MAX_SCREENS,targetProducts:TARGET_PRODUCTS,queue,results:[],summaries:[],status:'RUNNING'};const save=()=>fs.writeFileSync(path.join(root,'report.json'),JSON.stringify(report,null,2));save();
async function vmApi(route,body){const opt=body?{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({profileId:profile,body:Buffer.from(body).toString('base64')})}:{};const r=await fetch(vmBase+route+(body?'':(route.includes('?')?'&':'?')+'profileId='+profile),{...opt,signal:AbortSignal.timeout(20000)});const d=await r.json();if(d.status!=='OK'||d.success===false)throw Error('VMLogin '+JSON.stringify(d));return d;}
async function evaluate(code){const d=await vmApi('/ExecuteScript',code);return JSON.parse(d.value);}
async function post(route,data){const r=await fetch(base+route,{method:'POST',headers:{'Content-Type':'application/json','X-Pilot':'search-v1'},body:JSON.stringify(data)});const d=await r.json();if(!r.ok)throw Error(d.error);return d;}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));const scripts=['catalog-parser.js','temu-market-evidence.js','probe.js','screenshot-overlays.js'].map(n=>fs.readFileSync(path.join(import.meta.dirname,'extension',n),'utf8')).join('\n');
async function checkControl(){if(fs.existsSync(path.join(root,'STOP')))throw Error('Operator stopped trial');while(fs.existsSync(path.join(root,'PAUSE'))){report.status='PAUSED';save();await sleep(1000);if(fs.existsSync(path.join(root,'STOP')))throw Error('Operator stopped trial');}report.status='RUNNING';}
let pending=null;try{await runQueueItems(queue,async item=>{const capturedIds=new Set();let progress=null;report.current={anchor:item.anchor,query:item.query,unique:0,screens:0,target:TARGET_PRODUCTS};save();await checkControl();const before=await vmApi('/page/pagestate');if(new URL(before.baseURI).searchParams.get('search_key')!==item.query)await vmApi('/openurl?url='+encodeURIComponent('https://www.temu.com/de-en/search_result.html?search_key='+encodeURIComponent(item.query)));console.log('Search',item.anchor);await evaluate('JSON.stringify((()=>{window.scrollTo(0,0);return true})())');await sleep(2500);
for(let screen=1;screen<=MAX_SCREENS;screen++){await checkControl();let adjustments=0;let result=null,lastReason="页面尚未加载完成";for(let attempt=0;attempt<12;attempt++){await checkControl();const state=await vmApi('/page/pagestate');if(state.readyState==='complete'){try{const inspection=await evaluate(scripts+'\nJSON.stringify({result:inspectPilot('+JSON.stringify(item.query)+','+JSON.stringify([...capturedIds])+'),diagnostic:inspectPilot.lastReason,scrollAdjustment:inspectPilot.scrollAdjustment});');result=inspection?.result;lastReason=inspection?.diagnostic||lastReason;if((!result||!result.items.some(row=>!capturedIds.has(row.goods_id)))&&adjustments<2&&Number.isFinite(inspection?.scrollAdjustment)&&Math.abs(inspection.scrollAdjustment)>4){adjustments++;result=null;console.log('对齐未截图商品，滚动',inspection.scrollAdjustment);await evaluate('JSON.stringify((()=>{scrollBy(0,'+inspection.scrollAdjustment+');return true})())');await sleep(1000);}}catch(e){if(!/region|区域|商品区域|截图/.test(e.message))throw e;}if(result)break;}await sleep(1500);}if(!result)throw itemCaptureFailure('等待商品区域超时：'+lastReason);await sleep(1500);
await checkControl();const prepared=await post('/prepare',{...item});pending=await post('/start',{prepared_id:prepared.id});let bytes,meta,r,sx,sy,stableShot=false;
for(let captureAttempt=0;captureAttempt<2;captureAttempt++){
 await checkControl();let signature=null,settled=false;
 for(let settle=0;settle<8;settle++){const probe=await evaluate(scripts+'\nJSON.stringify(inspectPilot('+JSON.stringify(item.query)+'));');const key=probe?JSON.stringify({region:probe.region,y:probe.scroll_y,items:probe.items}):null;if(key&&key===signature){result=probe;settled=true;break;}signature=key;await sleep(1000);}
 if(!settled)throw itemCaptureFailure('页面商品布局持续变化，未取得稳定截图');
 const full=path.join(root,pending.id+'-attempt-'+captureAttempt+'-viewport.png');
 const overlayLease=await evaluate('JSON.stringify(TemuScreenshotOverlayGuard("hide"))');
 try{await sleep(150);await vmApi('/ScreenShot',full);let lastSize=0;for(let wait=0;wait<20;wait++){await sleep(500);const size=fs.existsSync(full)?fs.statSync(full).size:0;if(size>0&&size===lastSize)break;lastSize=size;}}
 finally{await evaluate('JSON.stringify(TemuScreenshotOverlayGuard("restore",'+JSON.stringify(overlayLease)+'))').catch(e=>console.warn('浮窗恢复等待自动保护计时器',e.message));}
 const afterShot=await evaluate(scripts+'\nJSON.stringify(inspectPilot('+JSON.stringify(item.query)+'));');
 if(!afterShot||JSON.stringify({region:afterShot.region,y:afterShot.scroll_y,items:afterShot.items})!==signature){console.log('Layout changed; retry screenshot only',captureAttempt+1);await sleep(1000);continue;}
 bytes=fs.readFileSync(full);meta=await sharp(bytes).metadata();r=result.region;sx=meta.width/r.viewportWidth;sy=meta.height/r.viewportHeight;if(Math.abs(sx-sy)>.02||sx<1||sx>4)throw Error('VMLogin screenshot is not viewport-sized');stableShot=true;break;
}
if(!stableShot)throw itemCaptureFailure('截图期间页面仍变化，已丢弃本屏；未重新搜索');
const crop=await sharp(bytes).extract({left:Math.round(r.x*sx),top:Math.round(r.y*sy),width:Math.round(r.width*sx),height:Math.round(r.height*sy)}).png().toBuffer();const cm=await sharp(crop).metadata();await post('/result',{...result,id:pending.id,token:pending.token,screenshot:{pngBase64:crop.toString('base64'),width:cm.width,height:cm.height}});report.results.push({anchor:item.anchor,query:item.query,screen,id:pending.id,items:result.items.map(i=>i.goods_id),url:base+'/?id='+pending.id});pending=null;for(const row of result.items)capturedIds.add(row.goods_id);progress=captureProgress([...capturedIds],screen);report.current={anchor:item.anchor,...progress};save();console.log('Saved',item.anchor,screen,result.items.length);if(progress.reason)break;
if(screen<MAX_SCREENS){await checkControl();const next=await evaluate(scripts+'\nJSON.stringify(nextPilotRow('+JSON.stringify([...capturedIds])+'));');if(!next){progress={...progress,reason:'LOADED_RESULTS_EXHAUSTED'};break;}console.log('按未截图商品行对齐',next.goods_id,next.delta);await evaluate('JSON.stringify((()=>{window.scrollTo(0,'+next.target+');return {ok:true}})())');await sleep(2000);}}
report.summaries.push({anchor:item.anchor,query:item.query,...progress,finished:new Date().toISOString()});save();},async(item,error)=>{
 let diagnostic=null;
 try{
  const current=await vmApi('/page/pagestate');if(new URL(current.baseURI).searchParams.get('search_key')===item.query){
   const id=globalThis.crypto.randomUUID(),folder=path.resolve(import.meta.dirname,'../../runtime/ui/screenshot-diagnostics');fs.mkdirSync(folder,{recursive:true});
   const observed=report.results.filter(r=>r.anchor===item.anchor&&r.query===item.query).flatMap(r=>r.items);
   const metadata=await evaluate(scripts+'\nJSON.stringify((()=>{inspectPilot('+JSON.stringify(item.query)+','+JSON.stringify(observed)+');return {geometry:inspectPilot.diagnostic,reason:inspectPilot.lastReason,adjustment:inspectPilot.scrollAdjustment}})());');
   const filename=path.join(folder,id+'.png'),lease=await evaluate('JSON.stringify(TemuScreenshotOverlayGuard("hide"))');
   try{await sleep(150);await vmApi('/ScreenShot',filename);for(let i=0;i<20&&!fs.existsSync(filename);i++)await sleep(500);}finally{await evaluate('JSON.stringify(TemuScreenshotOverlayGuard("restore",'+JSON.stringify(lease)+'))').catch(()=>{});}
   if(fs.existsSync(filename)&&fs.statSync(filename).size>0){fs.writeFileSync(path.join(folder,id+'.json'),JSON.stringify({anchor:item.anchor,query:item.query,created:new Date().toISOString(),...metadata},null,2));diagnostic={image:'http://127.0.0.1:37821/screenshot-diagnostics/'+id+'.png',details:'http://127.0.0.1:37821/screenshot-diagnostics/'+id+'.json',...metadata.geometry};}
  }
 }catch(e){console.warn('诊断截图未保存',e.message);}
 if(pending){await post('/fail',{id:pending.id,token:pending.token,error:error.message});pending=null;}
 const rows=report.results.filter(r=>r.anchor===item.anchor&&r.query===item.query);
 report.summaries.push({anchor:item.anchor,query:item.query,unique:new Set(rows.flatMap(r=>r.items)).size,screens:rows.length,target:TARGET_PRODUCTS,reason:'ITEM_FAILED',error:error.message,diagnostic,finished:new Date().toISOString()});
 save();console.warn('跳过当前商品，继续下一项',item.anchor,error.message);
});report.status=report.summaries.every(s=>s.reason==='TARGET_REACHED')?'DONE':'PARTIAL';}catch(e){report.status='STOPPED';report.error=e.message;console.error(e.message);if(pending)await post('/fail',{id:pending.id,token:pending.token,error:e.message}).catch(()=>{});}finally{report.finished=new Date().toISOString();save();console.log(JSON.stringify({status:report.status,screens:report.results.length,error:report.error}));}
