import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {createCatalogControl} from './catalog-vm-control.mjs';
import {validateCategoryUrl} from './catalog-vm-adapter.mjs';
const url='https://www.temu.com/de-en/replacement-parts-o3-123.html';
function fixture(t,{modify=()=>{},otherBusy=()=>false}={}){const root=fs.mkdtempSync(path.join(os.tmpdir(),'catalog-vm-test-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));let time=1000,count=40,y=0;const calls=[];const page=()=>({url,category:true,hidden:false,captcha:false,blocked:false,retry:false,empty:false,loading:false,ids:['a'],signature:'a',y,more:false,campaignId:'campaign1',count,runnerState:'PAGE_BOUND'});const adapter={profile:'fixture',current:async()=>url,open:async()=>{},inspect:async()=>page(),prepare:async()=>page(),capture:async()=>{calls.push('capture');count++;return page();},scroll:async()=>{calls.push('scroll');y+=500;},click:async(_u,text)=>calls.push(text)};modify(adapter,page,calls);const c=createCatalogControl({root,adapter,otherBusy,now:()=>time,wait:async ms=>{time+=ms;}});return {c,adapter,page,calls,root};}
async function prepare(c){c.act('detect');await c.settled();assert.equal(c.status().status,'READY');}
test('bind, collect until target, persist and require detection after restart',async t=>{const {c,calls,root}=fixture(t);await prepare(c);c.act('start',{target:2,minutes:30});await c.settled();assert.equal(c.status().status,'DONE');assert.equal(c.status().added,2);assert.equal(c.status().count,42);assert.equal(calls.filter(x=>x==='capture').length,2);const restored=createCatalogControl({root});assert.equal(restored.status().added,2);assert.equal(restored.status().canStart,false);});
test('captcha stops before any capture',async t=>{const f=fixture(t);await prepare(f.c);f.adapter.inspect=async()=>({...f.page(),captcha:true});f.c.act('start');await f.c.settled();assert.equal(f.c.status().status,'ERROR');assert.deepEqual(f.calls,[]);});
test('page change stops before capture',async t=>{const f=fixture(t);await prepare(f.c);f.adapter.inspect=async()=>({...f.page(),url:'https://www.temu.com/search_result.html'});f.c.act('start');await f.c.settled();assert.equal(f.c.status().status,'ERROR');assert.deepEqual(f.calls,[]);});
test('one retry then successful stable load',async t=>{let retry=false;const f=fixture(t);await prepare(f.c);retry=true;f.adapter.inspect=async()=>({...f.page(),retry,ids:retry?['a']:['a','b'],signature:retry?'a':'ab'});f.adapter.click=async(_u,text)=>{f.calls.push(text);retry=false;};f.c.act('start',{target:1});await f.c.settled();assert.equal(f.c.status().status,'DONE');assert.deepEqual(f.calls,['Try again','capture']);});
test('See more waits for changed stable products before next capture',async t=>{let loaded=false;const f=fixture(t);await prepare(f.c);f.adapter.inspect=async()=>({...f.page(),more:!loaded,ids:loaded?['a','b']:['a'],signature:loaded?'ab':'a'});f.adapter.click=async(_u,text)=>{f.calls.push(text);loaded=true;};f.c.act('start',{target:2});await f.c.settled();assert.equal(f.c.status().status,'DONE');assert.deepEqual(f.calls,['capture','See more','scroll','capture']);});
test('no new products after See more times out without another save',async t=>{const f=fixture(t);await prepare(f.c);f.adapter.inspect=async()=>({...f.page(),more:true});f.c.act('start',{target:2});await f.c.settled();assert.equal(f.c.status().status,'ERROR');assert.equal(f.calls.filter(x=>x==='capture').length,1);});
test('paused in-flight operation does not issue more work; stop preserves save',async t=>{const f=fixture(t);await prepare(f.c);let release,entered;const begun=new Promise(r=>entered=r);f.adapter.capture=async()=>{f.calls.push('capture');entered();await new Promise(r=>release=r);return {...f.page(),count:41};};f.c.act('start',{target:3});await begun;f.c.act('pause');assert.equal(f.c.status().status,'PAUSED');f.c.act('stop');release();await f.c.settled();assert.equal(f.c.status().status,'STOPPED');assert.equal(f.c.status().added,1);assert.deepEqual(f.calls,['capture']);});
test('screenshot queue mutex and URL validation',t=>{const f=fixture(t,{otherBusy:()=>true});assert.throws(()=>f.c.act('detect'),/截图队列/);assert.throws(()=>validateCategoryUrl('https://www.temu.com/search_result.html'));assert.throws(()=>validateCategoryUrl('https://evil.test/a-o3-123.html'));assert.equal(validateCategoryUrl(url),url);});

test('background category page can be collected without screenshots',async t=>{const f=fixture(t);await prepare(f.c);f.adapter.inspect=async()=>({...f.page(),hidden:true});f.c.act('start',{target:1});await f.c.settled();assert.equal(f.c.status().status,'DONE');assert.equal(f.c.status().added,1);});
