import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
import {createOpportunityReviews} from './opportunity-reviews.mjs';
import {createVmReviewClient,decodeVmValue} from './vm-review-client.mjs';
const id='601099591683955',url='https://www.temu.com/de-en/goods.html?goods_id='+id;
function fixture(t,{cards=[],otherBusy=()=>false,step,wait=async()=>{}}={}){const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE opportunities(goods_id TEXT,removed INTEGER)');db.prepare('INSERT INTO opportunities VALUES(?,0)').run(id);t.after(()=>db.close());const calls=[];let selected=1;const client={open:async x=>calls.push(['open',x]),step:step|| (async(_id,action)=>{calls.push([action]);if(action.startsWith('filter:')){selected=Number(action.split(':')[1]);return {phase:'FILTER_APPLIED'};}return action==='advance'?{phase:'END'}:{phase:'READY',cards:cards.filter(c=>!/^\d/.test(c.ratingText)||c.ratingText.startsWith(selected+' ')),url};})};const c=createOpportunityReviews(db,{client,otherBusy,wait,maxRounds:10});return {c,db,calls};}
const card=(rating,reviewId)=>({reviewId,dateText:'Sep 1, 2026',ratingText:rating,contentText:'The fitting broke during installation',rawText:'review'});
test('stores explicit negative reviews only, persists progress, repeats deduplicate',async t=>{const {c}=fixture(t,{cards:[card('1 out of 5 stars','one'),card('2 out of 5 stars','two'),card('5 out of 5 stars','five'),card('bad','unknown')]});c.act('start',{goodsIds:[id]});await c.settled();assert.equal(c.status().job.state,'DONE');assert.equal(c.status().job.inserted,2);assert.deepEqual(c.status().job.results[0].filters.map(f=>f.rating),[1,2]);assert.equal(c.reviews(id).items.length,2);assert.equal(c.reviews(id).listingDate,null);c.act('start',{goodsIds:[id]});await c.settled();assert.equal(c.status().job.inserted,0);assert.equal(c.reviews(id).items.length,2);});
test('challenge pauses and retains earlier saved batch',async t=>{let calls=0;const {c}=fixture(t,{step:async(_,action)=>{if(action.startsWith('filter:'))return {phase:'FILTER_APPLIED'};if(action==='advance')return {phase:'ADVANCED'};if(action!=='open'&&calls++)throw Error('需要人工验证');return {phase:'READY',url,cards:[card('1 out of 5 stars','one')]};}});c.act('start',{goodsIds:[id]});await c.settled();assert.equal(c.status().job.state,'PAUSED');assert.equal(c.reviews(id).items.length,1);});
test('empty unrecognized cards do not mean zero reviews',async t=>{const {c}=fixture(t);c.act('start',{goodsIds:[id]});await c.settled();assert.equal(c.status().job.state,'PAUSED');assert.match(c.status().job.message,/不能认定/);});
test('mutex, selection validation and restart preserve pending work',async t=>{const {c,db}=fixture(t,{otherBusy:()=>true});assert.throws(()=>c.act('start',{goodsIds:[id]}),/截图队列/);const payload={id:'restart',state:'RUNNING',goodsIds:[id],index:0};db.prepare('INSERT INTO opportunity_review_jobs VALUES(?,?,?,?)').run('restart','RUNNING',JSON.stringify(payload),'9999');const recovered=createOpportunityReviews(db);assert.equal(recovered.status().job.state,'PAUSED');assert.equal(recovered.status().job.index,0);});
test('API encodes script, guards current tab, handles nested exception',async()=>{assert.deepEqual(decodeVmValue({status:'OK',value:JSON.stringify({result:{result:{type:'string',value:JSON.stringify({phase:'READY'})}}})}),{phase:'READY'});assert.throws(()=>decodeVmValue({status:'OK',value:JSON.stringify({result:{exceptionDetails:{text:'wrong product'}}})}),/wrong product/);const calls=[];let selected=1;const client=createVmReviewClient({fetcher:async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>url.includes('pagestate')?{status:'OK',baseURI:'http://127.0.0.1:37822/auto'}:{status:'OK',value:JSON.stringify({phase:'READY'})}};}});await assert.rejects(()=>client.open(id),/切到 Temu/);await client.step(id,'read');const call=calls.at(-1);assert.match(call.url,/ExecuteScript$/);assert.equal(call.options.method,'POST');assert.match(Buffer.from(call.options.body.get('body'),'base64').toString(),/reviewPageStep/);});

test('rating-only review preserved with explicit rating evidence and reviewer',async t=>{const {c}=fixture(t,{cards:[{reviewId:null,reviewer:'Verified reader',ratingEvidence:'1 out of five stars',ratingText:'1 out of 5 stars',dateText:'Sep 1, 2026',contentText:'',rawText:''}]});c.act('start',{goodsIds:[id]});await c.settled();assert.equal(c.status().job.state,'PAUSED');assert.equal(c.reviews(id).items.length,1);assert.equal(c.reviews(id).items[0].content,'');});
test('wrong stars after selecting filter are never saved',async t=>{const {c}=fixture(t,{step:async(_,action)=>action.startsWith('filter:')?{phase:'FILTER_APPLIED'}:{phase:'READY',url,cards:[card('5 out of 5 stars','five')]}});c.act('start',{goodsIds:[id]});await c.settled();assert.equal(c.status().job.state,'PAUSED');assert.equal(c.reviews(id).items.length,0);assert.match(c.status().job.message,/星级不一致/);});
