import {createOpportunityReviews} from './opportunity-reviews.mjs';
import {createCatalogControl} from './catalog-vm-control.mjs';
import {createOpportunities} from './opportunities.mjs';
import {getGroup,setGroupRemoved,correctGroupFields} from './group-results.mjs';
import {createAutoControl} from './auto-control.mjs';
import {createRequire} from 'node:module';const sharp=createRequire(new URL('../../runtime/package.json',import.meta.url))('sharp');
import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {DatabaseSync} from 'node:sqlite';import {pathToFileURL} from 'node:url';
export function createPilot(root,{opportunityRoot=path.join(root,'opportunities')}={}){fs.mkdirSync(root,{recursive:true});const db=new DatabaseSync(path.join(root,'pilot.db'));db.exec(`CREATE TABLE IF NOT EXISTS runs(id TEXT PRIMARY KEY,token TEXT,status TEXT,query TEXT,anchor TEXT,created TEXT,error TEXT,result TEXT); CREATE TABLE IF NOT EXISTS exclusions(run_id TEXT,goods_id TEXT,removed INTEGER,PRIMARY KEY(run_id,goods_id)); CREATE TABLE IF NOT EXISTS audit(at TEXT,run_id TEXT,goods_id TEXT,action TEXT);`);
db.exec('CREATE TABLE IF NOT EXISTS prepared(id TEXT PRIMARY KEY,review_run TEXT,anchor TEXT,query TEXT,created TEXT)');if(!db.prepare('PRAGMA table_info(runs)').all().some(c=>c.name==='review_run'))db.exec('ALTER TABLE runs ADD COLUMN review_run TEXT');
const opportunities=createOpportunities(opportunityRoot,db);const autoControl=createAutoControl(db);const catalogControl=createCatalogControl({root:path.join(root,'catalog-auto-runs'),otherBusy:()=>autoControl.status().running});
const reviewControl=createOpportunityReviews(opportunities.db,{otherBusy:()=>autoControl.status().running||catalogControl.busy()});
const query='scooter with petrol inline fuel gas filter',anchor='601099512771916';const server=http.createServer(async(req,res)=>{function send(code,x){res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(x));}
try{const origin=req.headers.origin;if(origin&&!/^chrome-extension:\/\/[a-p]{32}$/.test(origin)&&origin!=='http://127.0.0.1:37822'&&origin!=='http://127.0.0.1:37821')return send(403,{error:'来源不允许'});if(origin)res.setHeader('Access-Control-Allow-Origin',origin);if(req.method==='OPTIONS'){res.setHeader('Access-Control-Allow-Methods','GET,POST');res.setHeader('Access-Control-Allow-Headers','Content-Type,X-Pilot');res.writeHead(204);return res.end();}const parsedUrl=new URL(req.url,'http://127.0.0.1'),route=parsedUrl.pathname;
if(req.method==='GET'&&route==='/catalog-auto'){res.writeHead(302,{'Location':'http://127.0.0.1:37821/#catalog','Cache-Control':'no-store'});return res.end();}
if(req.method==='POST'&&route.startsWith('/catalog-auto/'))return send(409,{error:'类目自动采集已暂停使用，请使用手动插件采集。'});
if(req.method==='GET'&&route==='/catalog-auto/status')return send(200,catalogControl.status());
if(req.method==='GET'&&route==='/catalog-auto'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});return res.end(fs.readFileSync(new URL('./catalog-auto.html',import.meta.url)));}
if(req.method==='GET'&&route==='/opportunities/reviews/status')return send(200,reviewControl.status());
if(req.method==='GET'&&route==='/opportunities/reviews/data')return send(200,reviewControl.reviews(parsedUrl.searchParams.get('goodsId')));
if(req.method==='GET'&&route==='/opportunity-reviews-ui.js'){res.writeHead(200,{'Content-Type':'text/javascript; charset=utf-8','Cache-Control':'no-store'});return res.end(fs.readFileSync(new URL('./opportunity-reviews-ui.js',import.meta.url)));}
if(req.method==='GET'&&route==='/opportunities/data')return send(200,{items:opportunities.list()});
if(req.method==='GET'&&route==='/opportunities'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});return res.end(fs.readFileSync(new URL('./opportunities.html',import.meta.url)));}
if(req.method==='GET'&&route==='/capture-group'){const id=parsedUrl.searchParams.get('id');const selected=db.prepare("SELECT * FROM runs WHERE id=? AND status='DONE'").get(id);if(!selected)throw Error('当前记录还没有截图');const folder=path.resolve(import.meta.dirname,'../../local-test/auto-search-trial');let ids=[id];for(const name of fs.readdirSync(folder).filter(n=>/^report(?:-\d+)?\.json$/.test(n))){let report;try{report=JSON.parse(fs.readFileSync(path.join(folder,name),'utf8'));}catch{continue;}if(report.results?.some(r=>r.id===id)){ids=report.results.filter(r=>r.anchor===selected.anchor&&r.query===selected.query).map(r=>r.id);break;}}const group=getGroup(db,ids);return send(200,{ids:group.runs.map(r=>r.id),count:group.runs.length});}
if(req.method==='GET'&&route==='/group')return send(200,getGroup(db,(parsedUrl.searchParams.get('ids')||'').split(',')));
if(req.method==='GET'&&route==='/combined'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});return res.end(fs.readFileSync(new URL('./combined.html',import.meta.url)));}
if(req.method==='GET'&&route==='/auto/status')return send(200,autoControl.status());
if(req.method==='GET'&&route==='/auto'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});return res.end(fs.readFileSync(new URL('./auto.html',import.meta.url)));}
if(req.method==='GET'&&route==='/prepared')return send(200,{prepared:db.prepare('SELECT * FROM prepared ORDER BY created DESC LIMIT 1').get()??null});
if(req.method==='GET'&&route==='/history')return send(200,{runs:db.prepare('SELECT id,review_run,anchor,query,status,created FROM runs WHERE (? IS NULL OR anchor=?) AND (? IS NULL OR review_run=? OR review_run IS NULL) ORDER BY created DESC').all(parsedUrl.searchParams.get('anchor'),parsedUrl.searchParams.get('anchor'),parsedUrl.searchParams.get('review_run'),parsedUrl.searchParams.get('review_run'))});
if(req.method==='GET'&&route==='/'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});return res.end(fs.readFileSync(new URL('./index.html',import.meta.url)));}
if(req.method==='GET'&&route==='/state'){const selected=parsedUrl.searchParams.get('id');const run=selected?db.prepare('SELECT id,status,query,anchor,review_run,created,error,result FROM runs WHERE id=?').get(selected):db.prepare('SELECT id,status,query,anchor,review_run,created,error,result FROM runs ORDER BY created DESC LIMIT 1').get();if(run){run.result=run.result?JSON.parse(run.result):null;run.removed=db.prepare('SELECT goods_id FROM exclusions WHERE run_id=? AND removed=1').all(run.id).map(r=>r.goods_id);}return send(200,{test_only:true,run:run??null,query,anchor});}
const shot=route.match(/^\/shots\/([a-f0-9-]+)$/);if(req.method==='GET'&&shot){const row=db.prepare('SELECT status FROM runs WHERE id=?').get(shot[1]);if(row?.status!=='DONE')return send(404,{error:'截图不存在'});res.writeHead(200,{'Content-Type':'image/png','Cache-Control':'no-store'});return res.end(fs.readFileSync(path.join(root,shot[1]+'.png')));}
if(req.method!=='POST')return send(404,{error:'无此接口'});if(req.headers['x-pilot']!=='search-v1')return send(403,{error:'缺少试跑标识'});
const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>8*1024*1024)return send(413,{error:'截图过大'});chunks.push(chunk);}const body=JSON.parse(Buffer.concat(chunks).toString());
if(route.startsWith('/opportunities/reviews/'))return send(200,reviewControl.act(route.slice('/opportunities/reviews/'.length),body));
if((route==='/auto/start'||route==='/start')&&reviewControl.busy())throw Error('差评采集正在控制 VMLogin，请先暂停并等待保存完成');
if(route==='/opportunities/save')return send(200,opportunities.save(body));
if(route==='/opportunities/update')return send(200,opportunities.update(body));
if(route==='/group/correct')return send(200,correctGroupFields(db,body));
if(route==='/group/remove'||route==='/group/restore')return send(200,setGroupRemoved(db,body.ids,body.goods_id,route==='/group/remove'));
if(route.startsWith('/catalog-auto/'))return send(200,catalogControl.act(route.slice(14),body));
if(route==='/auto/start'&&catalogControl.busy())throw Error('类目自动采集正在运行，请停止后再启动截图队列');
if(route.startsWith('/auto/'))return send(200,autoControl.act(route.slice(6),body));
if(route==='/prepare'){if(!/^\d{5,20}$/.test(body.anchor)||typeof body.query!=='string'||!body.query.trim()||body.query.length>500||typeof body.review_run!=='string'||!body.review_run.trim()||body.review_run.length>200)throw Error('商品、Review Run 或搜索词无效');const id=crypto.randomUUID();db.prepare('INSERT INTO prepared(id,review_run,anchor,query,created) VALUES(?,?,?,?,?)').run(id,body.review_run,body.anchor,body.query.trim(),new Date().toISOString());return send(200,{id});}
if(route==='/start'){const prepared=db.prepare('SELECT * FROM prepared WHERE id=?').get(body.prepared_id??'');if(!prepared)return send(400,{error:'请先在结果页确认当前商品和搜索词'});const latest=db.prepare("SELECT created FROM runs WHERE status='RUNNING' ORDER BY created DESC LIMIT 1").get();if(latest&&Date.now()-Date.parse(latest.created)<90000)return send(409,{error:'已有试跑进行中'});const id=crypto.randomUUID(),token=crypto.randomUUID();db.prepare('INSERT INTO runs(id,token,status,query,anchor,created,error,result,review_run) VALUES(?,?,?,?,?,?,?,?,?)').run(id,token,'RUNNING',prepared.query,prepared.anchor,new Date().toISOString(),null,null,prepared.review_run);return send(200,{id,token,query:prepared.query,anchor:prepared.anchor,review_run:prepared.review_run});}
const run=db.prepare('SELECT * FROM runs WHERE id=?').get(body.id);if(!run)return send(404,{error:'试跑不存在'});
if(route==='/remove'||route==='/restore'){if(run.status!=='DONE'||!JSON.parse(run.result).items.some(i=>i.goods_id===body.goods_id))return send(400,{error:'商品不属于此结果'});db.exec('BEGIN');try{db.prepare('INSERT INTO exclusions VALUES(?,?,?) ON CONFLICT(run_id,goods_id) DO UPDATE SET removed=excluded.removed').run(run.id,body.goods_id,route==='/remove'?1:0);db.prepare('INSERT INTO audit VALUES(?,?,?,?)').run(new Date().toISOString(),run.id,body.goods_id,route.slice(1));db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return send(200,{ok:true});}
if(body.token!==run.token||run.status!=='RUNNING')return send(409,{error:'试跑令牌或状态不匹配'});
if(route==='/fail'){db.prepare("UPDATE runs SET status='FAILED',error=? WHERE id=?").run(String(body.error).slice(0,600),run.id);return send(200,{ok:true});}
if(route!=='/result')return send(404,{error:'无此接口'});
if(body.query!==run.query||!Array.isArray(body.items)||body.items.length<1||body.items.length>12)throw Error('搜索词或商品数量无效');const url=new URL(body.page_url);if(url.origin!=='https://www.temu.com'||url.searchParams.get('search_key')!==run.query)throw Error('搜索地址不匹配');
const ids=new Set();const fields=['goods_id','title','price','currency','price_status','price_candidates','reference_prices','price_evidence','shot_rect','sales_count','rating','review_count'];const items=body.items.map(i=>{if(!/^\d{5,20}$/.test(i.goods_id)||ids.has(i.goods_id))throw Error('商品标识无效或重复');ids.add(i.goods_id);if(i.currency!==null&&i.currency!=='EUR')throw Error('币种不匹配');if(i.price!==null&&(!Number.isFinite(i.price)||i.price<0))throw Error('价格无效');return Object.fromEntries(fields.map(k=>[k,i[k]??null]));});
const region=body.region;if(!region||!['x','y','width','height','viewportWidth','viewportHeight'].every(k=>Number.isFinite(region[k]))||region.x<0||region.y<0||region.width<100||region.height<100||region.x+region.width>region.viewportWidth||region.y+region.height>region.viewportHeight)throw Error('截图区域无效');
const bytes=Buffer.from(body.screenshot?.pngBase64??'','base64');if(bytes.subarray(0,8).toString('hex')!=='89504e470d0a1a0a')throw Error('截图不是PNG');const meta=await sharp(bytes,{limitInputPixels:20000000}).metadata();if(meta.width!==body.screenshot.width||meta.height!==body.screenshot.height||meta.width/region.width<1||meta.width/region.width>4||Math.abs(meta.width/region.width-meta.height/region.height)>.02)throw Error('截图尺寸不匹配');
const result={items,region,page_url:body.page_url,screenshot_sha256:crypto.createHash('sha256').update(bytes).digest('hex'),received_at:new Date().toISOString()};fs.writeFileSync(path.join(root,run.id+'.png'),bytes,{flag:'wx'});db.prepare("UPDATE runs SET status='DONE',result=? WHERE id=?").run(JSON.stringify(result),run.id);return send(200,{ok:true,count:items.length});
}catch(e){send(400,{error:e.message});}});return{server,db};}
if(process.argv[1]&&pathToFileURL(path.resolve(process.argv[1])).href===import.meta.url){const app=createPilot(path.resolve(import.meta.dirname,'../../local-test/search-pilot'),{opportunityRoot:path.resolve(import.meta.dirname,'../../state/opportunities')});app.server.listen(37822,'127.0.0.1',()=>console.log('Search pilot http://127.0.0.1:37822'));}
