import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {createTrackingService,comparePoints} from '../../src/modules/tracking/tracking-service.mjs';
test('tracking freezes baseline, preserves periods, rejects stale data and survives restart',()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'period-test-')),source=new DatabaseSync(':memory:');
 source.exec(`CREATE TABLE catalog_pool_versions(id TEXT,category_key TEXT,product_count INTEGER,activated_at TEXT,status TEXT);CREATE TABLE catalog_pool_version_items(pool_version_id TEXT,staging_product_id INTEGER);CREATE TABLE catalog_staging_products(id INTEGER,category_key TEXT,platform TEXT,goods_id TEXT,latest_title TEXT,price_amount REAL,currency TEXT,sales_count INTEGER,review_count INTEGER,rating REAL,last_seen_at TEXT);INSERT INTO catalog_pool_versions VALUES('pool','parts',1,'2026-09-01','active');INSERT INTO catalog_pool_version_items VALUES('pool',1);INSERT INTO catalog_staging_products VALUES(1,'parts','temu','123','test',10,'EUR',100,10,4.5,'2026-09-01T00:00:00.000Z');`);
 let clock=Date.parse('2026-09-01T00:00:00.000Z');const options={sourceDb:source,databasePath:path.join(dir,'test.db'),now:()=>clock};let service=createTrackingService(options);
 try{const plan=service.create({poolId:'pool'});assert.equal(service.create({poolId:'pool'}).id,plan.id);assert.equal(plan.products[0].points[0].price_amount,10);
 clock+=7*86400000;assert.equal(service.sync().added,0);assert.equal(service.detail(plan.id).periods[0].status,'due');
 source.prepare('UPDATE catalog_staging_products SET price_amount=8,sales_count=120,last_seen_at=?').run(new Date(clock).toISOString());assert.equal(service.sync().added,1);assert.equal(service.sync().added,0);assert.equal(service.detail(plan.id).products[0].points.find(p=>p.day===0).price_amount,10);
 source.prepare('UPDATE catalog_staging_products SET price_amount=7,last_seen_at=?').run(new Date(clock+1000).toISOString());clock+=2000;service.sync();assert.equal(service.detail(plan.id).products[0].points.find(p=>p.day===7).price_amount,8);
 clock=Date.parse('2026-09-22T00:00:00Z');source.prepare('UPDATE catalog_staging_products SET price_amount=6,last_seen_at=?').run(new Date(clock).toISOString());service.sync();assert.equal(service.detail(plan.id).periods[1].status,'missed');assert.equal(service.detail(plan.id).products[0].points.filter(p=>p.day===14).length,0);
 service.close();service=createTrackingService(options);assert.equal(service.detail(plan.id).products[0].points.length,3);service.setStatus(plan.id,'paused');assert.equal(service.list().plans[0].status,'paused');assert.equal(source.prepare('SELECT count(*) n FROM catalog_staging_products').get().n,1);
 }finally{service.close();source.close();fs.rmSync(dir,{recursive:true,force:true});}
});
test('deltas preserve missing values and currency mismatch',()=>{assert.deepEqual(comparePoints({price_amount:10,currency:'EUR',sales_count:0,rating:4},{price_amount:8,currency:'USD',sales_count:2}),{price_delta:null,price_rate:null,sales_delta:2,review_delta:null,rating_delta:null});});

test('raw batch history wins over carried-forward staging values',()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'period-raw-')),source=new DatabaseSync(':memory:');
 source.exec(`CREATE TABLE catalog_pool_versions(id TEXT,category_key TEXT,product_count INTEGER,activated_at TEXT,status TEXT);CREATE TABLE catalog_pool_version_items(pool_version_id TEXT,staging_product_id INTEGER);CREATE TABLE catalog_staging_products(id INTEGER,category_key TEXT,platform TEXT,goods_id TEXT,price_amount REAL,currency TEXT,last_seen_at TEXT);CREATE TABLE catalog_campaigns(id TEXT,category_key TEXT);CREATE TABLE catalog_product_source_observations(id INTEGER,campaign_id TEXT,platform TEXT,goods_id TEXT,batch_id TEXT,observed_at TEXT,raw_json TEXT);INSERT INTO catalog_pool_versions VALUES('pool','parts',1,'2026-09-01','active');INSERT INTO catalog_pool_version_items VALUES('pool',1);INSERT INTO catalog_staging_products VALUES(1,'parts','temu','123',10,'EUR','2026-09-01T00:00:00.000Z');INSERT INTO catalog_campaigns VALUES('c','parts');`);
 let clock=Date.parse('2026-09-01T00:00:00Z');const service=createTrackingService({sourceDb:source,databasePath:path.join(dir,'test.db'),now:()=>clock});
 try{const p=service.create({poolId:'pool'});clock+=8*86400000;source.prepare('INSERT INTO catalog_product_source_observations VALUES(1,?,?,?,?,?,?)').run('c','temu','123','b','2026-09-08T00:00:00.000Z',JSON.stringify({price_amount:null,currency:'EUR',sales_count:140}));assert.equal(service.sync().added,1);const current=service.detail(p.id).products[0].points.find(p=>p.day===7);assert.equal(current.price_amount,null);assert.equal(current.sales_count,140);assert.equal(current.source_observation_id,1);assert.equal(service.sync().added,0);
 }finally{service.close();source.close();fs.rmSync(dir,{recursive:true,force:true});}
});
