import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import test from 'node:test';
import { openDatabase } from '../../src/db/client.mjs';
import { compareSafetyReports,parseSafetyArgs,verifySourcingSafety } from '../../scripts/1688/verify-sourcing-safety.mjs';

test('safety verifier writes complete read-only logical and raw evidence',async t=>{
  const dir=await fs.mkdtemp(path.join(os.tmpdir(),'sourcing-safety-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const temu=path.join(dir,'temu.db'),sourcing=path.join(dir,'sourcing.db'),raw=path.join(dir,'raw');await fs.mkdir(raw);await fs.writeFile(path.join(raw,'601.xlsx'),'raw');
  let db=openDatabase(temu,{allowRunnerWrite:true});db.exec("CREATE TABLE catalog_pool_versions(id TEXT,category_key TEXT,status TEXT,activated_at TEXT,product_count INTEGER);INSERT INTO catalog_pool_versions VALUES('pool','motorcycle-accessories','active','2026',2135);CREATE TABLE catalog_pool_version_items(id INTEGER,pool_version_id TEXT,goods_id TEXT);INSERT INTO catalog_pool_version_items VALUES(1,'pool','g1');CREATE TABLE products(id TEXT);INSERT INTO products VALUES('1');CREATE TABLE catalog_memberships(id TEXT);INSERT INTO catalog_memberships VALUES('m');");db.close();
  db=openDatabase(sourcing,{allowRunnerWrite:true});db.exec('CREATE TABLE x(id INTEGER PRIMARY KEY);INSERT INTO x VALUES(1)');db.close();const output=path.join(dir,'before.json');
  const before=await verifySourcingSafety({databasePath:temu,sourcingDatabasePath:sourcing,sourceDir:raw,workbookPath:path.join(dir,'analysis.xlsx'),fingerprintWorkbook:async()=>({valuesSha256:'sheet05'}),outputPath:output,label:'before-test'});assert.equal(before.pass,true);assert.equal(before.activePool.count,2135);assert.equal(before.temu.integrity,'ok');assert.equal(before.protectedTableCounts.products,1);assert.equal(before.sourcing.foreign_key_check,0);assert.equal(before.rawFiles.length,1);assert.equal(before.sheet05Fingerprint.valuesSha256,'sheet05');assert.equal(JSON.parse(await fs.readFile(output,'utf8')).label,'before-test');
  const after=await verifySourcingSafety({databasePath:temu,sourcingDatabasePath:sourcing,sourceDir:raw,workbookPath:path.join(dir,'analysis.xlsx'),fingerprintWorkbook:async()=>({valuesSha256:'sheet05'}),label:'after-test'});assert.equal(compareSafetyReports(before,after).pass,true);
  db=openDatabase(temu,{allowRunnerWrite:true});db.prepare("UPDATE products SET id='2'").run();db.close();const changed=await verifySourcingSafety({databasePath:temu,sourcingDatabasePath:sourcing,sourceDir:raw,workbookPath:path.join(dir,'analysis.xlsx'),fingerprintWorkbook:async()=>({valuesSha256:'sheet05'})});assert.equal(compareSafetyReports(before,changed).checks.temu_logical,false);
  db=openDatabase(temu,{allowRunnerWrite:true});db.prepare("UPDATE products SET id='1'").run();db.prepare("UPDATE catalog_pool_version_items SET goods_id='g2'").run();db.close();const changedPool=await verifySourcingSafety({databasePath:temu,sourcingDatabasePath:sourcing,sourceDir:raw,workbookPath:path.join(dir,'analysis.xlsx'),fingerprintWorkbook:async()=>({valuesSha256:'sheet05'})});assert.equal(compareSafetyReports(before,changedPool).checks.active_pool,false);
  const incomplete=await verifySourcingSafety({databasePath:temu});assert.equal(incomplete.pass,false);assert.equal(incomplete.evidenceComplete,false);assert.throws(()=>parseSafetyArgs(['node','script','before']),/sourceDir is required/);
});
