import {mountFinishCollection} from './finish-collection.js';
import {mountSystemLogs} from './system-logs.js';
import {mountPilotViews} from './pilot-views.js';
import {mountTrackingGrowth,openSourcingReview} from './tracking-growth.js';
import {mountManualRecapture} from './recapture-ui.js';
import {showTrackingTrend} from './tracking-trends.js';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'—';
const num=v=>Number.isFinite(v)?v.toLocaleString('zh-CN',{maximumFractionDigits:2}):'—';
const labels={scheduled:'未到期',due:'待采集 / 补齐',complete:'已记录',missed:'已过期 / 有缺失'};
const svg='<svg viewBox="0 0 24 24"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></svg>';
const views={overview:'工作台',catalog:'商品采集与商品池',sourcing:'1688 候选导入',tracking:'周期跟踪',diagnostics:'日志系统',auto:'自动截图队列',opportunities:'机会商品',collection:'辅助采集'};
document.body.insertAdjacentHTML('afterbegin',`<aside class="admin-sidebar"><div class="admin-brand"><b>T</b>Temu 运营台</div><nav class="admin-nav"><small>选品工作空间</small>${Object.entries(views).slice(0,4).map(([k,v])=>`<a href="#${k}" data-nav="${k}">${svg}${v}</a>`).join('')}<small>人工复核与任务</small><a id="admin-review-link" href="/#sourcing">${svg}1688 人工复核</a><a href="#auto" data-nav="auto">${svg}自动截图队列</a><a href="#opportunities" data-nav="opportunities">${svg}机会商品</a><a href="#diagnostics" data-nav="diagnostics">${svg}日志系统</a></nav><div class="admin-side-foot">德国站 · English · EUR<br>本机运营工作空间</div></aside><header class="admin-header"><div><button class="mobile-menu" aria-label="打开菜单">☰</button><span class="crumb">运营管理 /</span><strong id="admin-crumb">工作台</strong></div><div class="admin-user"><span>商品采集 · 寻源 · 趋势跟踪</span><span class="admin-avatar">运</span>运营人员</div></header><div class="admin-tabs"><span id="admin-tab">工作台</span></div>`);
const shell=$('.shell');
const pilotViews=mountPilotViews(shell);
const oldOverview=shell.querySelector(':scope > section.panel');oldOverview.dataset.view='overview';
$('#yingdao-module-root').dataset.view='sourcing';
$('#catalog-module-root').parentElement.dataset.view='catalog';
const legacy=[...shell.querySelectorAll(':scope > details')].find(e=>!e.dataset.view);if(legacy){legacy.hidden=true;legacy.style.display='none';}mountSystemLogs(shell);
shell.insertAdjacentHTML('afterbegin',`<div class="page-heading"><div><h1 id="admin-title">工作台</h1><p id="admin-subtitle">从商品采集到机会筛选，集中处理日常选品任务。</p></div><span class="tag">Temu · 德国站</span></div><div data-view="overview"><div class="admin-metrics" id="overview-metrics"></div><div class="admin-grid"><section class="panel"><h2>选品工作流程</h2>${[['建立商品池','采集商品，检查质量后建立正式商品池','catalog'],['1688 候选导入','关联 Temu ID，为每个商品抽取 5 个候选','sourcing'],['周期跟踪','按第 7 / 14 / 21 天对比价格与展示销量','tracking']].map(([a,b,c],i)=>`<div class="flow-row"><span class="flow-num">${i+1}</span><div><strong>${a}</strong><p>${b}</p></div><a href="#${c}">进入 →</a></div>`).join('')}</section><section class="panel"><h2>跟踪待办</h2><div id="overview-due" class="empty-state">加载中…</div></section></div></div>`);
shell.insertAdjacentHTML('beforeend',`<section data-view="tracking" hidden><div id="tracking-message" role="status" hidden></div><section class="panel"><div class="page-heading"><div><h2>跟踪计划</h2><p>固定商品池；同日相同指标合并，指标变化或隔天复采保留记录。</p></div><button id="track-refresh">刷新记录</button></div><form id="track-create" class="toolbar"><label>正式商品池 <select id="track-pool" required><option value="">加载中…</option></select></label><label>计划名称 <input id="track-name" maxlength="100" placeholder="例如：汽配商品 9 月跟踪"></label><button class="primary" type="submit">创建跟踪计划</button></form><div class="tracking-note">创建后保存现有商品池为基线。使用采集插件重新采集后，按实际时间归档，不限7/14/21天。同一天同一商品指标不变时不重复记录，日期按北京时间划分。7/14/21天仅作为原有阶段对比，完整历史请点“查看”。</div><div class="toolbar"><label>当前计划 <select id="track-plan"><option value="">暂无计划</option></select></label><button id="track-pause" disabled>暂停计划</button><button id="track-recapture" type="button">开始本轮复采 →</button></div></section><div id="track-detail" hidden><section class="panel" id="track-observation-summary" aria-live="polite"></section><p class="help">以下仅为第7、14、21天的阶段记录；未到期显示0，不影响上方累计复采记录。</p><div class="period-cards" id="track-periods"></div><section class="panel"><div class="toolbar"><label>对比周期 <select id="track-day"><option value="latest">最新数据 vs 基线</option><option value="7">第 7 天 vs 基线</option><option value="14">第 14 天 vs 基线</option><option value="21">第 21 天 vs 基线</option></select></label><input id="track-search" aria-label="搜索商品" placeholder="搜索商品标题 / Temu ID"><select id="track-filter" aria-label="筛选变化"><option value="all">全部商品</option><option value="observed">已获得后续观测</option><option value="changed">有指标变化</option><option value="missing">尚未观测到</option><option value="down">价格下降</option><option value="growth">展示销量增加</option></select><select id="track-sort" aria-label="排序"><option value="id">默认排序</option><option value="price">当前价格从低到高</option><option value="sales">展示销量增量从高到低</option></select><button id="track-export">导出周期 Excel</button></div><p class="help" id="track-baseline-note"></p><div class="table-scroll"><table class="admin-table"><thead><tr><th>商品</th><th>基线价格</th><th>本期价格</th><th>价格变化</th><th>展示销量变化 ≈</th><th>评论变化</th><th>评分变化</th><th>本期采集时间</th><th>趋势</th></tr></thead><tbody id="track-rows"></tbody></table></div><div class="pagination"><span id="track-page-label"></span><button id="track-prev">上一页</button><button id="track-next">下一页</button></div><p class="help">展示销量可能是取整数或区间值，增量不等于真实成交量；未采集到不代表下架。价格仅在币种相同时比较。</p></section></div></section><dialog class="trend-dialog" id="track-trend"><div class="page-heading"><h3>商品趋势</h3><button id="track-close">关闭</button></div><div id="track-trend-body"></div></dialog>`);
shell.insertAdjacentHTML('beforeend',`<section data-view="collection" hidden><p><a href="#catalog">← 返回商品采集与商品池</a></p><iframe title="辅助采集控制页面" src="/hybrid-collection.html" style="width:100%;height:calc(100vh - 220px);min-height:560px;border:0;border-radius:10px;background:#fff"></iframe></section>`);
function route(){let key=location.hash.slice(1);if(key==='yingdao-module-root')key='sourcing';if(key==='catalog-module-root')key='catalog';if(!views[key])key='overview';pilotViews.activate(key);document.querySelectorAll('[data-view]').forEach(e=>{e.hidden=e.dataset.view!==key;if(e.tagName==='DETAILS'&&!e.hidden)e.open=true;});document.querySelectorAll('[data-nav]').forEach(e=>e.classList.toggle('active',e.dataset.nav===(key==='collection'?'catalog':key)));for(const id of ['admin-title','admin-crumb','admin-tab'])$('#'+id).textContent=views[key];$('#admin-subtitle').textContent={overview:'从商品采集到机会筛选，集中处理日常选品任务。',catalog:'管理采集任务，建立正式商品池并导出商品与图片。',sourcing:'扫描 1688 Excel，随机抽取候选并关联 Temu 商品。',tracking:'保留每期历史记录，查看同一商品的指标变化。',diagnostics:'查看系统运行状态、错误记录；导出日志交给维护人员排查。',auto:'管理自动截图队列、运行进度和历史截图。',collection:'在运营台内启动采集、查看进度并处理暂停。',opportunities:'管理机会商品，采集差评并查看分析记录。'}[key];document.body.classList.remove('menu-open');}
window.addEventListener('hashchange',route);$('.mobile-menu').onclick=()=>document.body.classList.toggle('menu-open');route();
let state={pools:[],plans:[]},detail=null,page=1,visible=[];
const growth=mountTrackingGrowth({onTrend:p=>{showTrackingTrend(p,$('#track-trend-body'));$('#track-trend').showModal();}});
async function api(url,body){const res=await fetch('/api/tracking'+url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const data=await res.json();if(!res.ok||data.ok===false)throw Error(data.error?.message||'操作失败');return data;}
function message(text,error=false){const el=$('#tracking-message');el.hidden=false;el.className='admin-message'+(error?' error':'');el.textContent=text;}
async function refresh(){state=await api('');const old=$('#track-plan').value;$('#track-pool').innerHTML=state.pools.length?'<option value="">请选择需要跟踪的商品池</option>'+state.pools.map(p=>`<option value="${esc(p.id)}">${esc(p.category_key)} · ${p.product_count} 件</option>`).join(''):'<option value="">请先建立正式商品池</option>';$('#track-create button').disabled=!state.pools.length;$('#track-plan').innerHTML=state.plans.length?state.plans.map(p=>`<option value="${esc(p.id)}">${esc(p.name)} · ${p.product_count} 件${p.status==='paused'?' · 已暂停':''}</option>`).join(''):'<option value="">暂无计划</option>';if(state.plans.some(p=>p.id===old))$('#track-plan').value=old;const due=state.plans.filter(p=>p.status==='active').flatMap(p=>p.periods.filter(x=>x.status==='due').map(x=>({...x,name:p.name})));$('#overview-metrics').innerHTML=[['正式商品池',state.pools.length,'▦'],['池内商品',state.pools.reduce((n,p)=>n+p.product_count,0),'▤'],['跟踪计划',state.plans.length,'◷'],['到期待采集',due.length,'↻']].map(([a,b,c])=>`<div class="admin-metric"><div><label>${a}</label><strong>${num(b)}</strong></div><span class="metric-icon">${c}</span></div>`).join('');$('#overview-due').className='';$('#overview-due').innerHTML=due.length?due.map(p=>`<div class="flow-row"><div><strong>${esc(p.name)}</strong><p>第 ${p.day} 天 · 已记录 ${p.count}/${p.total} 件</p></div><a href="#tracking">查看 →</a></div>`).join(''):`<div class="empty-state">${state.plans.length?'目前没有到期任务':'暂无跟踪计划'}<br><a href="#tracking">进入周期跟踪 →</a></div>`;await load();}
async function load(){const id=$('#track-plan').value;detail=id?await api('/'+encodeURIComponent(id)):null;growth.update(detail);$('#track-detail').hidden=!detail;$('#track-pause').disabled=!detail;if(!detail)return;$('#track-pause').textContent=detail.status==='active'?'暂停计划':'恢复计划';$('#track-periods').innerHTML=detail.periods.map(p=>`<div class="period-card"><span class="tag ${p.status}">${labels[p.status]}</span><strong>第 ${p.day} 天</strong><div>${p.count} / ${p.total} 件已记录</div><small>到期 ${date(p.due_at)}<br>窗口截止 ${date(p.end_at)}</small></div>`).join('');$('#track-baseline-note').textContent=`计划开始：${date(detail.started_at)}。已保存 ${detail.products.reduce((n,p)=>n+(p.history?.length||0),0)} 条实际观测（含基线），点击“查看”可切换价格、销量、评论和评分曲线。`;const stats=observationStats();$('#track-observation-summary').innerHTML=`<h3>累计复采记录（不限日期）</h3><p><strong>${stats.updated} / ${stats.total} 件商品已更新 · ${stats.records} 条后续观测</strong></p><p>最近观测：${date(stats.latest)}。同日重复点击采集且指标不变时合并；原池商品的原始观测包含业务排除项，不等于插件的有效新增数量。</p><button id="track-show-updated" type="button">查看已更新商品</button>`;$('#track-show-updated').onclick=()=>{$('#track-day').value='latest';$('#track-filter').value='observed';page=1;render();$('#track-rows').scrollIntoView({block:'start'});};page=1;render();}
function observationStats(){const products=detail?.products??[];const rows=products.flatMap(p=>(p.history??[]).filter(h=>!h.is_baseline));return {updated:products.filter(p=>p.history?.some(h=>!h.is_baseline)).length,total:products.length,records:rows.length,latest:rows.reduce((a,r)=>!a||r.observed_at>a?r.observed_at:a,null)};}
function diff(b,c,k){return Number.isFinite(b?.[k])&&Number.isFinite(c?.[k])?c[k]-b[k]:null;}
function changes(p){const b=p.points.find(p=>p.day===0),c=$('#track-day').value==='latest'?(p.history?.filter(x=>!x.is_baseline).at(-1)??null):p.points.find(p=>p.day===Number($('#track-day').value));return {b,c,price:b?.currency&&b.currency===c?.currency?diff(b,c,'price_amount'):null,sales:diff(b,c,'sales_count'),reviews:diff(b,c,'review_count'),rating:diff(b,c,'rating')};}
function change(n){return n==null?'—':`${n>0?'+':''}${num(n)}`;}
function render(){if(!detail)return;const q=$('#track-search').value.toLowerCase(),filter=$('#track-filter').value;visible=detail.products.map(p=>({...p,...changes(p)})).filter(p=>(p.goods_id+' '+p.title).toLowerCase().includes(q)).filter(p=>filter==='all'||filter==='observed'&&Boolean(p.c)||filter==='changed'&&[p.price,p.sales,p.reviews,p.rating].some(n=>n!==null&&n!==0)||filter==='missing'&&!p.c||filter==='down'&&p.price<0||filter==='growth'&&p.sales>0);const sort=$('#track-sort').value;if(sort==='price')visible.sort((a,b)=>(a.c?.price_amount??Infinity)-(b.c?.price_amount??Infinity));if(sort==='sales')visible.sort((a,b)=>(b.sales??-Infinity)-(a.sales??-Infinity));const pages=Math.max(1,Math.ceil(visible.length/20));page=Math.min(page,pages);$('#track-rows').innerHTML=visible.slice((page-1)*20,page*20).map(p=>`<tr><td><div class="product-cell">${/^https:\/\//.test(p.image_url||'')?`<img src="${esc(p.image_url)}" loading="lazy" referrerpolicy="no-referrer" alt="">`:''}<div><span title="${esc(p.title)}">${esc(p.title||'未命名商品')}</span><small>${esc(p.goods_id)}</small></div></div></td><td>${num(p.b?.price_amount)} ${esc(p.b?.currency||'')}</td><td>${p.c?num(p.c.price_amount)+' '+esc(p.c.currency||''):'—'}</td><td class="${p.price>0?'positive':p.price<0?'negative':''}">${change(p.price)}</td><td>${change(p.sales)}</td><td>${change(p.reviews)}</td><td>${change(p.rating)}</td><td>${p.c?date(p.c.last_seen_at):'<span class="tag">尚未观测到</span>'}</td><td><button data-trend="${esc(p.goods_id)}">查看</button><button data-review-go="${esc(p.goods_id)}">1688 复核 →</button></td></tr>`).join('')||'<tr><td colspan="9" class="empty-state">没有符合条件的商品</td></tr>';$('#track-page-label').textContent=`共 ${visible.length} 件 · ${page} / ${pages} 页`;$('#track-prev').disabled=page<=1;$('#track-next').disabled=page>=pages;}
async function action(fn,button){if(button)button.disabled=true;try{await fn();}catch(e){message(e.message,true);}finally{if(button)button.disabled=false;}}
$('#track-create').onsubmit=e=>{e.preventDefault();action(async()=>{const d=await api('/create',{poolId:$('#track-pool').value,name:$('#track-name').value});await refresh();$('#track-plan').value=d.id;await load();message('计划已保存；指标变化或隔天复采保留记录，不用等满7天。');},e.submitter);};
$('#track-refresh').onclick=e=>action(async()=>{const r=await api('/sync',{});await refresh();const stats=observationStats();message(`已刷新：当前计划累计 ${stats.updated} 件商品更新、${stats.records} 条后续观测。本次同步新增 ${r.added} 条（所有计划）；0表示没有尚未归档的新记录，不代表未采集。`);},e.currentTarget);
$('#track-plan').onchange=()=>action(load);$('#track-pause').onclick=e=>action(async()=>{await api('/'+detail.id+'/status',{status:detail.status==='active'?'paused':'active'});await refresh();},e.currentTarget);
for(const s of ['day','filter','sort'])$('#track-'+s).onchange=()=>{page=1;render();};$('#track-search').oninput=()=>{page=1;render();};$('#track-prev').onclick=()=>{page--;render();};$('#track-next').onclick=()=>{page++;render();};
$('#track-export').onclick=e=>action(async()=>{const res=await fetch('/api/tracking/'+detail.id+'/export');if(!res.ok){const j=await res.json();throw Error(j.error?.message||'导出失败');}const blob=await res.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='周期跟踪-'+detail.category_key+'.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);message('周期 Excel 已生成，浏览器正在下载。');},e.currentTarget);
$('#track-rows').onclick=e=>{const target=e.target.closest('[data-review-go]');if(target){action(()=>openSourcingReview(target.dataset.reviewGo),target);return;}const id=e.target.closest('[data-trend]')?.dataset.trend;if(!id)return;showTrackingTrend(detail.products.find(p=>p.goods_id===id),$('#track-trend-body'));$('#track-trend').showModal();};$('#track-close').onclick=()=>$('#track-trend').close();
refresh().catch(e=>{message(e.message,true);$('#overview-due').textContent='数据加载失败：'+e.message;});

fetch("/api/sourcing/review/runs").then(r=>r.json()).then(d=>{if(d.runs?.length)$("#admin-review-link").href="/sourcing-review.html?"+new URLSearchParams({run_id:d.runs[0].run_id});}).catch(()=>{});

mountManualRecapture();mountFinishCollection();

$('#track-recapture').onclick=e=>action(async()=>{await load();if(!detail)throw Error('请先选择跟踪计划');const snapshot=await fetch('/api/catalog/manual-tasks').then(r=>{if(!r.ok)throw Error('任务读取失败');return r.json();});const response=await fetch('/api/catalog/manual-tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({poolId:detail.pool_id,name:(detail.name||'跟踪计划')+' · '+new Date().toLocaleString('zh-CN')+'复采',requestId:crypto.randomUUID(),expectedCurrentId:snapshot.current?.id??null,expectedGeneration:snapshot.current?.generation??null})});const result=await response.json();if(!response.ok)throw Error(result.error?.message||'创建复采任务失败');location.hash='collection';},e.currentTarget);
