export function mountManualRecapture(){
 const host=document.querySelector('[data-view="catalog"]');if(!host)return;
 const panel=document.createElement('section');panel.className='panel';panel.id='manual-recapture';
 panel.innerHTML='<h2>已有商品复采（周期跟踪）</h2><p>重新采集正式池内商品，记录价格、销量和评论变化。不要求新增数量，不覆盖正式商品池。新类目的首次采集使用上方“新建采集任务”。</p><div class="toolbar"><label>正式商品池 <select id="recapture-pool"></select></label><label>任务名称 <input id="recapture-name" placeholder="可留空，自动命名"></label><button id="recapture-create">新建一轮周期复采</button></div><p>切换会暂停当前手动任务并保留进度。切换后，在 Temu 打开对应类目，重新检测、绑定，再手动采集。</p><div class="toolbar"><label>选择要继续的旧任务 <select id="recapture-task"></select></label><button id="recapture-switch">继续这个任务</button><button id="recapture-refresh">刷新任务</button><button id="recapture-pause" type="button">暂停当前任务，释放采集占用</button></div><p id="recapture-message" role="status"></p><hr><h3>将本次复采商品合并到正式池</h3><p>选择上方已有复采任务，先预览合并数量。原池商品保留，新品去重加入；新池保存独立数据副本，原池和旧跟踪计划历史保留。</p><button id="merge-preview" type="button">预览所选复采任务的合并结果</button><p id="merge-summary" role="status"></p><button id="merge-confirm" type="button" hidden>确认合并到正式池</button> <button id="merge-track" type="button" hidden>为合并后的商品池创建跟踪计划</button>';
 host.append(panel);const q=s=>panel.querySelector(s);
 const resume=document.createElement('section');resume.id='existing-task-entry';resume.style.cssText='padding:16px;border:1px solid #c8d8e8;border-radius:8px;margin-bottom:24px;background:#f5f9ff';
 resume.innerHTML='<h2>继续已有任务（接着上次采集）</h2><p>不用填写新任务名称，也不会创建新任务。选择原任务后点击“继续这个任务”，已采商品和进度会接着累积。</p><p id="active-task-summary" role="status"></p>';
 resume.append(q('#recapture-task').closest('.toolbar'),q('#recapture-message'));panel.prepend(resume);const tip=document.createElement('a');tip.href='#merge-preview';tip.textContent='已完成采集？选好对应任务，去预览入池数量 →';tip.onclick=e=>{e.preventDefault();q('#merge-preview').scrollIntoView({behavior:'smooth'});};resume.append(tip);const next=document.getElementById('catalog-next-sourcing');if(next)panel.append(next);

 const createTitle=panel.querySelector(':scope > h2');if(createTitle)createTitle.textContent='更新已有商品数据（周期复采）';
 const periodic=document.createElement('section');periodic.innerHTML='';
 const nodes=[...panel.children];let collecting=false;for(const node of nodes){if(node===createTitle)collecting=true;if(node.tagName==='HR')break;if(collecting)periodic.append(node);}resume.after(periodic);

 const modes=document.createElement('section');modes.className='panel';modes.innerHTML='<h2>你现在要做什么？</h2><div class="toolbar"><button data-mode="new">采集新品</button><button data-mode="continue">继续上次</button><button data-mode="update">更新已有商品</button></div><p id="catalog-mode-tip"></p>';host.prepend(modes);
 periodic.id='periodic-recapture-entry';
 const style=document.createElement('style');style.textContent='[data-view="catalog"][data-mode="continue"] #catalog-panel > :not(#catalog-current-campaign),[data-view="catalog"][data-mode="update"] #catalog-panel > :not(#catalog-current-campaign){display:none!important}';document.head.append(style);
 function selectMode(mode){host.dataset.mode=mode;resume.hidden=mode!=='continue';periodic.hidden=mode!=='update';modes.querySelectorAll('button').forEach(b=>{b.classList.toggle('primary',b.dataset.mode===mode);b.setAttribute('aria-pressed',String(b.dataset.mode===mode));});modes.querySelector('p').textContent={new:'选择类目并创建任务，再进入辅助采集。',continue:'选择原任务，进度保留；继续后进入采集控制。',update:'选择已有商品池，创建新一轮复采；按已有商品覆盖情况显示进度。'}[mode];}
 modes.querySelectorAll('button').forEach(b=>b.onclick=()=>selectMode(b.dataset.mode));selectMode('continue');
 const instructions=document.getElementById('catalog-manual-bind-steps');if(instructions)instructions.innerHTML='<h3>采集步骤</h3><p>选好任务 → 进入辅助采集 → 检查并开始 → 5秒内切回VMLogin商品页。检测通过后自动绑定并采集；验证码或登录由人工处理。</p>';
 panel.querySelector('#merge-preview').textContent='预览并合并到正式商品池';
 const mergeHeading=panel.querySelector(':scope > h3');if(mergeHeading)mergeHeading.textContent='4. 预览采集结果并入池';

let state=null,busy=false,requestId=null;let syncedCategory=null;document.addEventListener('catalog-category-selected',e=>{if(!state||e.detail===syncedCategory)return;const pool=state.pools.find(p=>p.category_key===e.detail);if(pool){q('#recapture-pool').value=pool.id;syncedCategory=e.detail;}});
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const names={'motorcycle-accessories':'摩托车配件','replacement-parts':'替换零件'};
 async function api(body){const r=await fetch('/api/catalog/manual-tasks',{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error?.message||'任务操作失败');return d;}
 let mergePreview=null,mergeResult=null,mergeRequest=null;
 async function mergeApi(body){const url='/api/catalog/recapture-pool-merge'+(body?'':'?campaignId='+encodeURIComponent(q('#recapture-task').value));const r=await fetch(url,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error?.message||'合并失败');return d;}
 q('#merge-preview').onclick=async()=>{if(busy)return;busy=true;q('#merge-preview').disabled=true;q('#merge-confirm').hidden=true;q('#merge-track').hidden=true;try{mergePreview=await mergeApi();mergeRequest=crypto.randomUUID();const m=mergePreview;q('#merge-summary').textContent=`${m.campaignName}：原池 ${m.previousCount} 件，本次已采 ${m.capturedCount} 件，加入新品 ${m.added} 件，更新已有 ${m.updated} 件，合并后 ${m.total} 件。筛选未通过 ${m.excluded} 件不加入。`;q('#merge-confirm').hidden=false;}catch(e){q('#merge-summary').textContent=e.message;}finally{busy=false;q('#merge-preview').disabled=false;}};
 q('#merge-confirm').onclick=async()=>{if(busy||!mergePreview)return;busy=true;q('#merge-confirm').disabled=true;try{mergeResult=await mergeApi({campaignId:mergePreview.campaignId,revision:mergePreview.revision,requestId:mergeRequest});q('#merge-summary').textContent=`正式池已保存，共 ${mergeResult.total} 件（新增 ${mergeResult.added} 件）。旧池和旧计划历史保留。下一步点击创建跟踪计划。`;q('#merge-confirm').hidden=true;q('#merge-track').hidden=false;await refresh();}catch(e){q('#merge-summary').textContent=e.message;}finally{busy=false;q('#merge-confirm').disabled=false;}};
 q('#merge-track').onclick=async()=>{if(!mergeResult||busy)return;busy=true;q('#merge-track').disabled=true;try{const r=await fetch('/api/tracking/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({poolId:mergeResult.poolId,name:`${names[mergeResult.category]||mergeResult.category} · ${mergeResult.total}件跟踪`})});const d=await r.json();if(!r.ok)throw Error(d.error?.message||'创建跟踪计划失败');location.href='/#tracking';location.reload();}catch(e){q('#merge-summary').textContent='正式池已合并；'+e.message+'，可以重试创建跟踪计划。';}finally{busy=false;q('#merge-track').disabled=false;}};
 q('#recapture-task').onchange=()=>{mergePreview=null;q('#merge-confirm').hidden=true;};
 async function refresh(){state=await api();const chosen=q('#recapture-pool').value,chosenTask=q('#recapture-task').value;
  q('#recapture-pool').innerHTML=state.pools.map(p=>`<option value="${esc(p.id)}">${esc(names[p.category_key]||p.category_key)} · ${esc(p.category_key)} · ${p.product_count} 件</option>`).join('');const category=document.querySelector('#catalog-category-select')?.value;const matching=state.pools.find(p=>p.category_key===category);if(matching)q('#recapture-pool').value=matching.id;else if(state.pools.some(p=>p.id===chosen))q('#recapture-pool').value=chosen;
  q('#recapture-task').innerHTML=state.tasks.map(t=>`<option value="${esc(t.id)}">${esc(t.name)} · ${esc(t.purpose)} · ${t.count} 件 · ${t.id===state.current?.id?'当前任务':t.status==='paused'?'已暂停':esc(t.status)}</option>`).join('');
  if(state.tasks.some(t=>t.id===chosenTask))q('#recapture-task').value=chosenTask;else if(state.current)q('#recapture-task').value=state.current.id;q('#active-task-summary').textContent=state.current?'当前正在使用：'+(state.tasks.find(t=>t.id===state.current.id)?.name||state.current.id)+'。若继续此任务，回 Temu 插件采集即可；只有换任务时才需点击下面按钮。':'当前没有正在使用的任务，请选择原任务继续。';
  q('#recapture-pause').disabled=!state.current;q('#recapture-pause').title=state.current?'暂停的是当前占用中的任务，保留全部已采数据':'目前没有活跃采集任务';q('#recapture-create').disabled=!state.pools.length;q('#recapture-switch').disabled=!state.tasks.length;
 }
 async function run(create){if(busy||!state)return;busy=true;panel.querySelectorAll('button').forEach(b=>b.disabled=true);q('#recapture-message').textContent='正在切换任务…';try{
  requestId??=crypto.randomUUID();await api({...create?{poolId:q('#recapture-pool').value,name:q('#recapture-name').value,requestId}:{campaignId:q('#recapture-task').value},expectedCurrentId:state.current?.id??null,expectedGeneration:state.current?.generation??null});requestId=null;
  await refresh();if(state.current)q('#recapture-task').value=state.current.id;q('#recapture-message').textContent='任务已切换，即将进入采集控制。';location.hash='collection';
 }catch(e){q('#recapture-message').textContent=e.message;await refresh().catch(()=>{});}finally{busy=false;q('#recapture-refresh').disabled=false;q('#merge-preview').disabled=false;q('#merge-confirm').disabled=false;q('#merge-track').disabled=false;}}
 q('#recapture-pause').onclick=async()=>{if(busy||!state?.current)return;busy=true;q('#recapture-pause').disabled=true;try{const r=await fetch('/api/catalog/manual-tasks/pause',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedCurrentId:state.current.id,expectedGeneration:state.current.generation})});const d=await r.json();if(!r.ok)throw Error(d.error?.message||'暂停失败');await refresh();q('#recapture-message').textContent='当前任务已暂停，采集占用已释放，已采数据保留。现在可在上方创建新类目首次任务；以后选中旧任务，点击“继续这个任务”即可恢复。';}catch(e){q('#recapture-message').textContent=e.message;await refresh().catch(()=>{});}finally{busy=false;q('#recapture-pause').disabled=!state?.current;}};
 q('#recapture-create').onclick=()=>run(true);q('#recapture-switch').onclick=()=>run(false);q('#recapture-refresh').onclick=()=>refresh().catch(e=>q('#recapture-message').textContent=e.message);
 q('#recapture-pool').onchange=q('#recapture-name').oninput=()=>{requestId=null;};
 document.addEventListener('tracking-recapture',async e=>{location.hash='catalog';await refresh();if(state.pools.some(p=>p.id===e.detail.poolId))q('#recapture-pool').value=e.detail.poolId;panel.scrollIntoView({block:'start'});});
 document.querySelector('#catalog-category-select')?.addEventListener('change',()=>refresh().catch(e=>q('#recapture-message').textContent=e.message));
 refresh().catch(e=>q('#recapture-message').textContent=e.message);
}
