const DAY=86400000;
export const chinaDate=value=>new Date(value).toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'});
export function growthInWindow(product,{start,end,minimum=1000}){
  const rows=(product.history||[]).filter(r=>Number.isFinite(r.sales_count)&&Number.isFinite(Date.parse(r.observed_at||r.last_seen_at))).map(r=>({...r,at:Date.parse(r.observed_at||r.last_seen_at)})).filter(r=>r.at>=start&&r.at<=end).sort((a,b)=>a.at-b.at);
  if(rows.length<2||rows[0].at===rows.at(-1).at)return {status:'insufficient',product};
  if(rows.some((r,i)=>i>0&&r.sales_count<rows[i-1].sales_count))return {status:'reset',product};
  const first=rows[0],last=rows.at(-1),delta=last.sales_count-first.sales_count;
  return {status:delta>=minimum?'match':'below',product,first,last,delta,days:(last.at-first.at)/DAY};
}
async function getJson(url){const r=await fetch(url),d=await r.json();if(!r.ok)throw Error(d.error?.message||'读取候选批次失败');return d;}
export async function openSourcingReview(goodsId){
  const {runs}=await getJson('/api/sourcing/review/runs');
  for(const run of runs||[]){const data=await getJson('/api/sourcing/review/bootstrap?'+new URLSearchParams({run_id:run.run_id,filter:'ALL'}));
    if(data.goods?.some(p=>String(p.temu_goods_id)===String(goodsId))){location.assign('/sourcing-review.html?'+new URLSearchParams({run_id:run.run_id,goods_id:goodsId,from:'tracking'}));return;}}
  throw Error('商品 '+goodsId+' 尚无已导入的 1688 候选，请先为该商品导入候选，再进行人工复核。');
}
export function mountTrackingGrowth({onTrend}={}){
  const root=document.createElement('section');root.className='panel';root.id='track-growth';root.innerHTML=`<style>#track-growth .admin-table{table-layout:fixed;width:100%;min-width:980px}#track-growth .admin-table td,#track-growth .admin-table th{white-space:normal;overflow-wrap:anywhere}#track-growth .admin-table th:first-child{width:24%}#track-growth .admin-table th:nth-child(2){width:26%}#track-growth .admin-table th:last-child{width:20%}#track-growth .admin-table td:first-child{white-space:pre-line}#track-growth .growth-product{display:flex;gap:10px;align-items:center;min-width:0}#track-growth .growth-product img{width:44px;height:44px;object-fit:contain;flex:none}#track-growth .growth-copy{min-width:0}#track-growth .growth-title{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}#track-growth .growth-copy small{display:block;color:#7b8491;font-size:12px}#track-growth .growth-error{color:#b54708;font-size:12px;line-height:1.5;margin-top:8px}</style><h3>按销量增长发现机会商品</h3><div class="toolbar"><label>时间范围 <select id="growth-period"><option value="7">近 7 天</option><option value="30">近 30 天（一个月）</option><option value="custom">自定义日期</option></select></label><label>开始日期 <input type="date" id="growth-start"></label><label>结束日期 <input type="date" id="growth-end"></label><label>展示销量至少增加 <input id="growth-min" type="number" min="0" step="1" value="1000" style="width:110px"></label><button id="growth-apply" type="button">筛选机会商品</button></div><p class="help">按北京时间选择日期；比较窗口内最早和最新两次有效观测，不补值、不外推。实际跨度可能短于所选窗口；展示销量为近似值，不等于真实成交量。</p><p id="growth-summary" role="status"></p><div class="table-scroll"><table class="admin-table"><thead><tr><th>商品 / Temu ID</th><th>实际观测区间</th><th>起始展示销量 ≈</th><th>最新展示销量 ≈</th><th>窗口内增量 ≈</th><th>操作</th></tr></thead><tbody id="growth-rows"></tbody></table></div><div class="pagination"><button id="growth-prev">上一页</button><span id="growth-page"></span><button id="growth-next">下一页</button></div>`;
  document.getElementById('track-observation-summary').after(root);const q=id=>root.querySelector('#'+id);let detail=null,page=1,matches=[];
  function preset(){if(q('growth-period').value==='custom')return;const days=Number(q('growth-period').value),today=chinaDate(Date.now());q('growth-end').value=today;q('growth-start').value=chinaDate(Date.parse(today+'T00:00:00+08:00')-(days-1)*DAY);}
  function render(){q('growth-rows').replaceChildren();const total=Math.max(1,Math.ceil(matches.length/20));page=Math.min(page,total);q('growth-page').textContent=page+' / '+total+' 页';q('growth-prev').disabled=page<=1;q('growth-next').disabled=page>=total;
    for(const row of matches.slice((page-1)*20,page*20)){const tr=document.createElement('tr');tr.dataset.goodsId=row.product.goods_id;const productCell=document.createElement('td'),productBox=document.createElement('div'),copy=document.createElement('div'),title=document.createElement('span'),goods=document.createElement('small');productBox.className='growth-product';copy.className='growth-copy';title.className='growth-title';title.textContent=row.product.title||'未命名商品';title.title=title.textContent;goods.textContent=row.product.goods_id;const imageUrl=row.product.image_url||row.last.image_url||row.first.image_url;if(/^https:\/\//.test(imageUrl||'')){const img=document.createElement('img');img.src=imageUrl;img.alt='商品图片';img.loading='lazy';img.referrerPolicy='no-referrer';img.onerror=()=>{const placeholder=document.createElement('span');placeholder.textContent='图片未加载';placeholder.style.cssText='width:44px;min-width:44px;font-size:11px;color:#8993a1;background:#f3f5f7;text-align:center;padding:6px 0';img.replaceWith(placeholder);};productBox.append(img);}copy.append(title,goods);productBox.append(copy);productCell.append(productBox);tr.append(productCell);for(const value of [new Date(row.first.at).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})+' → '+new Date(row.last.at).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})+'（'+row.days.toFixed(1)+' 天）',row.first.sales_count.toLocaleString(),row.last.sales_count.toLocaleString(),'+'+row.delta.toLocaleString()]){const td=document.createElement('td');td.textContent=value;tr.append(td);}const td=document.createElement('td');const trend=document.createElement('button');trend.textContent='查看趋势';trend.onclick=()=>onTrend?.(row.product);const review=document.createElement('button');review.textContent='去 1688 人工复核 →';const feedback=document.createElement('div');feedback.className='growth-error';feedback.setAttribute('role','alert');review.onclick=async()=>{review.disabled=true;review.textContent='正在查找候选…';feedback.textContent='';try{await openSourcingReview(row.product.goods_id);}catch(e){feedback.textContent=e.message;}finally{review.disabled=false;review.textContent='去 1688 人工复核 →';}};td.append(trend,review,feedback);tr.append(td);q('growth-rows').append(tr);}
    if(!matches.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=6;td.textContent='当前没有达到条件的商品；可调整时间范围或在复采后刷新记录。';tr.append(td);q('growth-rows').append(tr);}}
  function apply(){page=1;const start=Date.parse(q('growth-start').value+'T00:00:00+08:00'),end=Date.parse(q('growth-end').value+'T23:59:59.999+08:00'),minimum=Number(q('growth-min').value);if(!Number.isFinite(start)||!Number.isFinite(end)||start>end||q('growth-min').value===''||!Number.isFinite(minimum)||minimum<0){matches=[];render();q('growth-summary').textContent='请填写有效日期范围和非负增量。';return;}
    const rows=(detail?.products||[]).map(p=>growthInWindow(p,{start,end,minimum}));matches=rows.filter(r=>r.status==='match').sort((a,b)=>b.delta-a.delta);q('growth-summary').textContent=`符合条件 ${matches.length} 件 · 数据不足 ${rows.filter(r=>r.status==='insufficient').length} 件 · 窗口内销量回退、需复核 ${rows.filter(r=>r.status==='reset').length} 件`;render();}
  q('growth-period').onchange=()=>{preset();apply();};for(const id of ['growth-start','growth-end'])q(id).onchange=()=>{q('growth-period').value='custom';apply();};q('growth-apply').onclick=apply;q('growth-min').onchange=apply;q('growth-prev').onclick=()=>{page--;render();};q('growth-next').onclick=()=>{page++;render();};preset();
  return {update(value){detail=value;apply();}};
}
