const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=v=>Number.isFinite(v)?v.toLocaleString('zh-CN',{maximumFractionDigits:2}):'—';
const stamp=v=>Number.isFinite(typeof v==='number'?v:Date.parse(v))?new Date(v).toLocaleString('zh-CN',{hour12:false}):'—';
const metrics={price_amount:'价格',sales_count:'展示销量（约）',review_count:'评论数',rating:'评分'};
export function showTrackingTrend(product,root){
 const rows=product.history?.length?product.history:product.points||[];
 root.innerHTML=`<p>${esc(product.title)}</p><small>${esc(product.goods_id)} · ${rows.length} 次观测（含基线）</small><p><label>曲线指标 <select id="trend-metric">${Object.entries(metrics).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label></p><div id="trend-chart"></div><p class="help">按实际采集时间记录。空缺不补值；展示销量差额不是精确成交量。没有新增采集记录时，不推测期间变化。</p><div style="max-height:300px;overflow:auto"><table class="admin-table"><thead><tr><th>实际采集时间</th><th>价格</th><th>展示销量 ≈</th><th>评论 / 评分</th><th>较上次：价格 / 销量 / 评论</th></tr></thead><tbody>${[...rows].reverse().map(r=>`<tr><td>${stamp(r.observed_at||r.last_seen_at)}${r.is_baseline?' · 基线':''}</td><td>${number(r.price_amount)} ${esc(r.currency||'')}</td><td>${number(r.sales_count)}</td><td>${number(r.review_count)} / ${number(r.rating)}</td><td>${number(r.changes?.price_delta)} / ${number(r.changes?.sales_delta)} / ${number(r.changes?.review_delta)}</td></tr>`).join('')}</tbody></table></div>`;
 const draw=()=>{const metric=root.querySelector('#trend-metric').value,valid=rows.filter(r=>Number.isFinite(r[metric])&&Number.isFinite(Date.parse(r.observed_at||r.last_seen_at)));const chart=root.querySelector('#trend-chart');if(!valid.length){chart.textContent='这个指标暂无有效数据';return;}const times=rows.map(r=>Date.parse(r.observed_at||r.last_seen_at)).filter(Number.isFinite),t0=Math.min(...times),t1=Math.max(...times),values=valid.map(r=>r[metric]),min=Math.min(...values),max=Math.max(...values),x=r=>60+(Date.parse(r.observed_at||r.last_seen_at)-t0)/(t1-t0||1)*550,y=r=>155-(r[metric]-min)/(max-min||1)*110;let lines='';
 for(let i=1;i<rows.length;i++){const a=rows[i-1],b=rows[i];if(!valid.includes(a)||!valid.includes(b)||metric==='price_amount'&&(!a.currency||a.currency!==b.currency))continue;lines+=`<line x1="${x(a)}" y1="${y(a)}" x2="${x(b)}" y2="${y(b)}" stroke="#409eff" stroke-width="2"/>`;}
 chart.innerHTML=`<svg viewBox="0 0 660 215" role="img" aria-label="${metrics[metric]}按实际采集时间变化" style="width:100%"><line x1="60" y1="165" x2="620" y2="165" stroke="#dcdfe6"/><text x="8" y="50" font-size="11" fill="#737b88">${number(max)}</text><text x="8" y="158" font-size="11" fill="#737b88">${number(min)}</text>${lines}${valid.map(r=>`<circle cx="${x(r)}" cy="${y(r)}" r="4" fill="#409eff"><title>${esc(stamp(r.observed_at||r.last_seen_at)+' · '+number(r[metric])+(metric==='price_amount'?' '+(r.currency||''):''))}</title></circle>`).join('')}<text x="60" y="195" font-size="11" fill="#737b88">${esc(stamp(t0))}</text><text x="620" y="195" text-anchor="end" font-size="11" fill="#737b88">${esc(stamp(t1))}</text></svg>`;};
 root.querySelector('#trend-metric').onchange=draw;draw();
}
