import assert from 'node:assert/strict';import crypto from 'node:crypto';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import test from 'node:test';
import { buildImportQa,classifyImageRecheck,selectManualAuditGoods } from '../../src/modules/sourcing/sourcing-import-qa.mjs';
import {createManualAuditArtifacts} from '../../src/modules/sourcing/manual-audit-artifacts.mjs';

const clean=overrides=>({sourceExportFiles:2,parsedFiles:2,failedFiles:[],uniqueTemuGoodsId:2,totalSourceCandidates:8,goodsIds:['601','602'],candidates:[
  {temu_goods_id:'601',supplier_product_id:'p1',candidate_rank:1,supplier_image_url:'https://img/p1.jpg',image_download_status:'SUCCESS',image_sha256:'a'},
  {temu_goods_id:'602',supplier_product_id:'p2',candidate_rank:1,supplier_image_url:'https://img/p2.jpg',image_download_status:'FAILED'},
],invalidDownloadedImage:0,imageMappingError:0,reproducible:true,...overrides});

test('mandatory QA gate failure blocks PASS and exact metrics are present',()=>{
  const report=buildImportQa(clean({imageMappingError:1}));
  assert.equal(report.pass,false);assert.match(report.final_status,/BLOCKED/);
  for(const name of ['source_export_files','parsed_files','failed_files','unique_temu_goods_id','total_source_candidates','goods_sampled','samples_total','goods_with_5','goods_with_less_than_5','duplicate_1688_product_id_within_goods','duplicate_temu_1688_pair','image_url_retained','image_download_success','image_download_failed','invalid_downloaded_image','image_mapping_error','random_sampling_reproducible']) assert.ok(Object.hasOwn(report,name),name);
});
test('clean fixture yields PASS',()=>{const report=buildImportQa(clean());assert.equal(report.pass,true);assert.equal(report.random_sampling_reproducible,'PASS');});
test('manual field mismatch blocks PASS without being mislabeled as image mapping error',()=>{const report=buildImportQa(clean({manualFieldError:1}));assert.equal(report.pass,false);assert.equal(report.manual_field_error,1);assert.equal(report.image_mapping_error,0);});
test('source manifest mismatch blocks PASS',()=>{const report=buildImportQa(clean({manifestMatches:false}));assert.equal(report.pass,false);assert.equal(report.source_manifest_matches,'FAIL');});
test('manual 10 goods selection is stable and input-order independent',()=>{const ids=Array.from({length:25},(_,i)=>String(1000+i));assert.deepEqual(selectManualAuditGoods(ids),selectManualAuditGoods([...ids].reverse()));assert.equal(selectManualAuditGoods(ids).length,10);});
test('changed CDN response is inconclusive, not a mapping error',()=>{assert.equal(classifyImageRecheck({recordedResponseSha:'a',recheckedResponseSha:'b',mappingValid:true}),'SOURCE_CHANGED/RECHECK_INCONCLUSIVE');assert.equal(classifyImageRecheck({recordedResponseSha:'a',recheckedResponseSha:'a',mappingValid:false}),'MAPPING_ERROR');assert.equal(classifyImageRecheck({recordedResponseSha:null,recheckedResponseSha:'a',mappingValid:true}),'RECHECK_INCONCLUSIVE');});
test('manual audit writes stable JSON and one contact sheet per selected goods',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'manual-evidence-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const cache=path.join(dir,'cache'),sheets=path.join(dir,'sheets'),bytes=Buffer.from('jpeg-fixture'),sha=crypto.createHash('sha256').update(bytes).digest('hex'),candidates=[];for(let i=0;i<12;i++){const goods=String(100+i),product=`p${i}`,relative=`${goods}/${product}.jpg`;await fs.mkdir(path.dirname(path.join(cache,relative)),{recursive:true});await fs.writeFile(path.join(cache,relative),bytes);candidates.push({temu_goods_id:goods,supplier_product_id:product,candidate_rank:1,original_rank:1,supplier_image_url:'https://img/x.jpg',supplier_image_local_path:relative,image_sha256:sha,image_response_sha256:'old',image_download_status:'SUCCESS'});}const fakeSharp=input=>input?.create?{composite:()=>({jpeg:()=>({toFile:async file=>fs.writeFile(file,'sheet')})})}:{resize:()=>({jpeg:()=>({toBuffer:async()=>bytes})})};const report=await createManualAuditArtifacts({candidates,imageCacheRoot:cache,outputPath:path.join(dir,'manual-audit-10.json'),contactSheetDir:sheets,sharpFactory:fakeSharp,cacheImage:async(candidate,{cacheRoot})=>{const relative=`${candidate.temu_goods_id}/${candidate['1688_product_id']}.jpg`;await fs.mkdir(path.dirname(path.join(cacheRoot,relative)),{recursive:true});await fs.writeFile(path.join(cacheRoot,relative),bytes);return{image_download_status:'SUCCESS','1688_image_local_path':relative,image_response_sha256:'new'};}});assert.equal(report.selected_goods_ids.length,10);assert.equal((await fs.readdir(sheets)).length,10);assert.ok(report.items.every(x=>x.candidates[0].status==='SOURCE_CHANGED/RECHECK_INCONCLUSIVE'));});
test('FAILED image without cache baseline remains inconclusive instead of mapping error',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'manual-failed-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const goods=Array.from({length:10},(_,i)=>String(300+i));const candidates=goods.map((id,i)=>({temu_goods_id:id,supplier_product_id:`p${i}`,candidate_rank:1,original_rank:1,supplier_image_url:'https://img/fail.jpg',supplier_image_local_path:null,image_sha256:null,image_response_sha256:null,image_download_status:'FAILED'}));const fakeSharp=input=>input?.create?{composite:()=>({jpeg:()=>({toFile:async file=>fs.writeFile(file,'sheet')})})}:{resize:()=>({jpeg:()=>({toBuffer:async()=>Buffer.from('x')})})};const report=await createManualAuditArtifacts({candidates,imageCacheRoot:path.join(dir,'cache'),outputPath:path.join(dir,'audit.json'),contactSheetDir:path.join(dir,'sheets'),sharpFactory:fakeSharp,cacheImage:async()=>({image_download_status:'FAILED'})});assert.ok(report.items.every(x=>x.candidates[0].status==='RECHECK_INCONCLUSIVE'));});
