import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const root=path.resolve(import.meta.dirname,'../..'),ext=name=>fs.readFileSync(path.join(root,'browser-extension',name),'utf8');
const fixture=()=>JSON.parse(fs.readFileSync(path.join(root,'test/fixtures/temu-poppy-opt-sanitized.json'),'utf8'));
const liveIdFixture=()=>JSON.parse(fs.readFileSync(path.join(root,'test/fixtures/temu-live-goods-ids-sanitized.json'),'utf8'));
const BRIDGE_FILES=['catalog-network-endpoints.js','catalog-network-parser.js','catalog-network-cache.js','catalog-product-merger.js','catalog-network-bridge.js'];
function sandbox(files,extra={}){const value={console,URL,Date,Set,Map,...extra};value.globalThis=value;value.window=value;vm.createContext(value);for(const file of files)vm.runInContext(ext(file),value);return value;}
function envelope(type,payload,nonce='nonce_test',overrides={}){return {source:'temu-network-interceptor',type,version:1,message_id:'msg_test',nonce,payload,...overrides};}
function invoke(s,data,origin='https://www.temu.com'){s.__bridgeData=data;s.__bridgeOrigin=origin;return vm.runInContext('TemuCatalogNetworkBridge.handle({source:window,origin:__bridgeOrigin,data:__bridgeData})',s);}
function ready(s,nonce='nonce_test'){return invoke(s,envelope('TEMU_CATALOG_NETWORK_INTERCEPTOR_READY',{installedAt:1.25,documentReadyState:'loading',timeOrigin:1000},nonce));}
function bridgeHarness(){const listeners={},messages=[];const s={console,URL,Date,Set,Map,location:{href:'https://www.temu.com/de-en/',origin:'https://www.temu.com',protocol:'https:',hostname:'www.temu.com'},document:{readyState:'loading'},performance:{now:()=>1.5,timeOrigin:1000},crypto:{randomUUID:()=> 'nonce_harness'},setTimeout:fn=>{fn();return 1;},addEventListener:(type,fn)=>{(listeners[type]??=[]).push(fn);}};s.globalThis=s;s.window=s;vm.createContext(s);for(const file of BRIDGE_FILES)vm.runInContext(ext(file),s);s.postMessage=data=>{messages.push(data);invoke(s,data);};vm.runInContext(ext('temu-network-interceptor.js'),s);return {s,messages};}
function splitWorldHarness({isolatedFiles=BRIDGE_FILES}={}){
  const messages=[],location={href:'https://www.temu.com/de-en/motorcycles--accessories-o3-585.html?opt_level=2&title=Motorcycles%20%26%20Powersports%20Accessories',origin:'https://www.temu.com',protocol:'https:',hostname:'www.temu.com'};
  const isolated=sandbox(isolatedFiles,{location,addEventListener:()=>{}});
  const main=sandbox(['catalog-network-endpoints.js'],{location,document:{readyState:'loading'},performance:{now:()=>1.5,timeOrigin:1000},crypto:{randomUUID:()=> 'nonce_split'},setTimeout:fn=>{fn();return 1;},addEventListener:()=>{}});
  main.postMessage=data=>{messages.push(data);invoke(isolated,JSON.parse(JSON.stringify(data)));};
  vm.runInContext(ext('temu-network-interceptor.js'),main);
  return {main,isolated,messages};
}

test('network endpoint normalization accepts localized Temu opt only',()=>{const s=sandbox(['catalog-network-endpoints.js']);const e=s.TemuCatalogNetworkEndpoints;assert.equal(e.normalizeTemuApiPath('/de-en/api/poppy/v1/opt'),'/api/poppy/v1/opt');assert.equal(e.normalizeTemuApiPath('/de/api/poppy/v1/opt'),'/api/poppy/v1/opt');assert.equal(e.normalizeTemuApiPath('/fr-en/api/poppy/v1/opt'),'/api/poppy/v1/opt');assert.equal(e.isCatalogProductEndpoint('https://www.temu.com/de-en/api/poppy/v1/opt'),true);assert.equal(e.captureMode('https://www.temu.com/de-en/api/poppy/v1/opt'),'diagnostic_parse');assert.equal(e.isCatalogProductEndpoint('https://evil.example/de-en/api/poppy/v1/opt'),false);});

test('goods identity contract preserves observed 15 and 16 digit strings exactly',()=>{const s=sandbox(['catalog-network-endpoints.js']);const e=s.TemuCatalogNetworkEndpoints;for(const id of ['601099602102774','6017592186107580','000000000000001'])assert.equal(e.normalizeGoodsId(id),id);assert.equal(e.GOODS_ID_MAX_LENGTH,16);});

test('goods identity contract rejects over-bound, empty and null values',()=>{const s=sandbox(['catalog-network-endpoints.js']);const normalize=s.TemuCatalogNetworkEndpoints.normalizeGoodsId;for(const id of ['12345678901234567','',null,undefined,'12x'])assert.equal(normalize(id),null);});

test('runtime parser owns the identity contract instead of silently requiring an optional global',()=>{const s=sandbox(['catalog-network-parser.js']);const normalize=s.TemuCatalogNetworkParser.normalizeGoodsId;for(const id of ['601099602102774','6017592186107580','000000000000001'])assert.equal(normalize(id),id);for(const id of ['12345678901234567','',null,undefined,'12x'])assert.equal(normalize(id),null);assert.equal(s.TemuCatalogNetworkParser.NETWORK_RUNTIME_VERSION,'track-a-runtime-v2');assert.equal(s.TemuCatalogNetworkParser.IDENTITY_CONTRACT_VERSION,'track-a-id-v2');});

test('parser reports endpoint rejection before collection when no helper or bridge proof exists',()=>{const s=sandbox(['catalog-network-parser.js']),analysis=s.TemuCatalogNetworkParser.analyzeProductRecords([{goods_id:'601099602102774'}],{endpoint:'/api/poppy/v1/opt',base:'https://www.temu.com/de-en/motorcycles--accessories-o3-585.html'});assert.equal(analysis.status,'endpoint_rejected');assert.equal(analysis.stage,'endpoint_gate');assert.equal(analysis.records.length,0);assert.equal(analysis.invalid.length,0);assert.equal(analysis.diagnostics.parser_endpoint_allowed,false);assert.equal(analysis.diagnostics.parser_endpoint_helper_available,false);assert.equal(analysis.diagnostics.parser_collect_attempted,false);});

test('separate MAIN and ISOLATED worlds use the runtime parser entry and expose matching versions',()=>{const {main,isolated}=splitWorldHarness();const ids=['601099602102774','6017592186107580','000000000000001'];const projected=ids.map(goods_id=>main.TemuCatalogNetworkInterceptor.projectProduct({goods_id,title:'x'}));assert.deepEqual(projected.map(row=>row.goods_id),ids);main.TemuCatalogNetworkInterceptor.sendProducts(main,{products:projected});const d=isolated.TemuCatalogNetworkCache.diagnostics(ids);assert.equal(d.network_runtime_version,'track-a-runtime-v2');assert.equal(d.identity_contract_version,'track-a-id-v2');assert.equal(d.isolated_network_runtime_version,'track-a-runtime-v2');assert.equal(d.isolated_identity_contract_version,'track-a-id-v2');assert.equal(d.network_parse_successes,1);assert.equal(d.network_parse_errors,0);assert.equal(d.network_cache_size,3);for(const id of ids)assert.equal(isolated.TemuCatalogNetworkCache.get(id).goods_id,id);});

test('bridge proof removes the live optional endpoint-helper dependency in separate worlds',()=>{const isolatedFiles=['catalog-network-parser.js','catalog-network-cache.js','catalog-product-merger.js','catalog-network-bridge.js'],{main,isolated,messages}=splitWorldHarness({isolatedFiles}),products=liveIdFixture().products.slice(0,20);main.TemuCatalogNetworkInterceptor.sendProducts(main,{products});const d=isolated.TemuCatalogNetworkCache.diagnostics(products.map(x=>x.goods_id)),stage=d.parser_stage;assert.equal(messages.filter(x=>x.type==='TEMU_CATALOG_NETWORK_PRODUCTS').length,1);assert.equal(d.parser_endpoint_gate_version,'track-a-parser-endpoint-v3');assert.equal(stage.parser_endpoint_raw,'/api/poppy/v1/opt');assert.equal(stage.parser_endpoint_type,'string');assert.equal(stage.parser_base,'https://www.temu.com/de-en/motorcycles--accessories-o3-585.html');assert.equal(stage.parser_endpoint_normalized,'/api/poppy/v1/opt');assert.equal(stage.parser_endpoint_helper_available,false);assert.equal(stage.parser_endpoint_allowed,true);assert.equal(stage.parser_endpoint_validation_source,'bridge');assert.equal(stage.parser_collect_attempted,true);assert.equal(stage.parser_records_count,20);assert.equal(stage.parser_invalid_identity_count,0);assert.equal(d.network_parse_successes,1);assert.equal(d.network_parse_errors,0);assert.equal(d.network_cache_size,20);});

test('separate-world runtime rejects invalid identities before formal cache insertion',()=>{const {main,isolated}=splitWorldHarness();const invalid=['12345678901234567','',null,'12x'];for(const goods_id of invalid)assert.equal(main.TemuCatalogNetworkInterceptor.projectProduct({goods_id}).goods_id,undefined);main.TemuCatalogNetworkInterceptor.sendProducts(main,{products:invalid.map(goods_id=>({goods_id}))});assert.equal(isolated.TemuCatalogNetworkCache.diagnostics().network_cache_size,0);});

test('all MAIN messages use one JSON-compatible envelope',()=>{const {s,messages}=bridgeHarness();s.TemuCatalogNetworkInterceptor.sendProducts(s,{synthetic:true,products:[{goods_id:'900000000000001',title:'Bridge Smoke Product',ignored:undefined}]});const message=messages.find(row=>row.type==='TEMU_CATALOG_NETWORK_PRODUCTS');assert.equal(message.source,'temu-network-interceptor');assert.equal(message.version,1);assert.equal(message.nonce,'nonce_harness');assert.match(message.message_id,/^msg_/);assert.doesNotMatch(JSON.stringify(message),/ignored/);});

test('synthetic MAIN to ISOLATED delivery inserts one cache record',()=>{const {s}=bridgeHarness();const result=s.TemuCatalogNetworkInterceptor.sendProducts(s,{synthetic:true,products:[{goods_id:'900000000000001',title:'Bridge Smoke Product'}]});assert.equal(result[0].sent,true);const d=s.TemuCatalogNetworkCache.diagnostics();assert.equal(d.main_products_message_sent,1);assert.equal(d.isolated_products_message_received,1);assert.equal(d.network_parse_successes,1);assert.equal(d.bridge_schema_rejected,0);assert.equal(d.cache_inserted_goods,1);assert.equal(s.TemuCatalogNetworkCache.get('900000000000001').latestProduct.title,'Bridge Smoke Product');});

test('bridge rejects invalid source without accepting products',()=>{const s=sandbox(BRIDGE_FILES,{location:{href:'https://www.temu.com/de-en/',origin:'https://www.temu.com',protocol:'https:',hostname:'www.temu.com'},addEventListener:()=>{}});ready(s);const bad=envelope('TEMU_CATALOG_NETWORK_PRODUCTS',{endpoint:'/api/poppy/v1/opt',observed_at:'now',products:[{goods_id:'1'}]});bad.source='wrong';assert.equal(invoke(s,bad),false);assert.equal(s.TemuCatalogNetworkCache.records.size,0);});

test('bridge rejects unknown type and counts it',()=>{const s=sandbox(BRIDGE_FILES,{location:{href:'https://www.temu.com/de-en/',origin:'https://www.temu.com',protocol:'https:',hostname:'www.temu.com'},addEventListener:()=>{}});ready(s);assert.equal(invoke(s,envelope('UNKNOWN_TYPE',{})),false);assert.equal(s.TemuCatalogNetworkCache.diagnostics().bridge_unknown_type,1);});

test('bridge rejects version mismatch',()=>{const s=sandbox(BRIDGE_FILES,{location:{href:'https://www.temu.com/de-en/',origin:'https://www.temu.com',protocol:'https:',hostname:'www.temu.com'},addEventListener:()=>{}});const message=envelope('TEMU_CATALOG_NETWORK_INTERCEPTOR_READY',{},'nonce_test',{version:2});assert.equal(invoke(s,message),false);assert.equal(s.TemuCatalogNetworkCache.diagnostics().bridge_schema_rejected,1);});

test('bridge rejects nonce mismatch and exposes expected and received values',()=>{const s=sandbox(BRIDGE_FILES,{location:{href:'https://www.temu.com/de-en/',origin:'https://www.temu.com',protocol:'https:',hostname:'www.temu.com'},addEventListener:()=>{}});ready(s,'expected');const message=envelope('TEMU_CATALOG_NETWORK_PRODUCTS',{endpoint:'/api/poppy/v1/opt',observed_at:'now',products:[{goods_id:'1'}]},'received');assert.equal(invoke(s,message),false);const d=s.TemuCatalogNetworkCache.diagnostics();assert.equal(d.bridge_nonce_expected,'expected');assert.equal(d.bridge_nonce_received,'received');assert.equal(d.bridge_nonce_mismatch_count,1);});

test('plain-object serialization removes undefined and unrelated nested data',()=>{const {s,messages}=bridgeHarness();s.TemuCatalogNetworkInterceptor.sendProducts(s,{products:[{goods_id:'1',title:'A',token:'secret',price_amount:9,extra:{x:1},missing:undefined}]});const message=messages.find(row=>row.type==='TEMU_CATALOG_NETWORK_PRODUCTS');assert.deepEqual(Object.keys(message.payload.products[0]).sort(),['goods_id','price_amount','title']);assert.doesNotMatch(JSON.stringify(message),/secret|token|extra|missing/);});

test('generic or out-of-range score cannot poison an otherwise valid product chunk',()=>{const {s}=bridgeHarness();const rows=[{goods_id:'11',title:'A',score:96},{goods_id:'12',title:'B',rating:48},{goods_id:'13',title:'C',rating:4.8}];const result=s.TemuCatalogNetworkInterceptor.sendProducts(s,{products:rows});assert.equal(result[0].sent,true);const d=s.TemuCatalogNetworkCache.diagnostics();assert.equal(d.bridge_schema_rejected,0);assert.equal(d.cache_inserted_goods,3);assert.equal(s.TemuCatalogNetworkCache.get('11').latestProduct.rating,null);assert.equal(s.TemuCatalogNetworkCache.get('12').latestProduct.rating,null);assert.equal(s.TemuCatalogNetworkCache.get('13').latestProduct.rating,4.8);});

test('invalid optional fields degrade to null without rejecting a valid goods id',()=>{const s=sandbox(BRIDGE_FILES,{location:{href:'https://www.temu.com/de-en/',origin:'https://www.temu.com',protocol:'https:',hostname:'www.temu.com'},addEventListener:()=>{}});ready(s);const message=envelope('TEMU_CATALOG_NETWORK_PRODUCTS',{endpoint:'/api/poppy/v1/opt',observed_at:'now',products:[{goods_id:'14',title:7,image_url:{bad:true},currency:false,price_amount:'bad',sales_count:-1,rating:48,review_count:'bad'}]});assert.equal(invoke(s,message),true);const row=s.TemuCatalogNetworkCache.get('14').latestProduct;assert.deepEqual({title:row.title,image_url:row.image_url,currency:row.currency,price_amount:row.price_amount,sales_count:row.sales_count,rating:row.rating,review_count:row.review_count},{title:null,image_url:null,currency:null,price_amount:null,sales_count:null,rating:null,review_count:null});assert.equal(s.TemuCatalogNetworkCache.diagnostics().bridge_schema_rejected,0);});

test('oversized product envelope is rejected before postMessage',()=>{const {s,messages}=bridgeHarness();const huge=Array.from({length:20},(_,i)=>({goods_id:String(1000+i),title:'x'.repeat(300),image_url:'y'.repeat(300),currency:'z'.repeat(300),price_amount:i,sales_count:i,rating:4,review_count:i}));const before=messages.length;const result=s.TemuCatalogNetworkInterceptor.sendProducts(s,{products:huge});assert.equal(result[0].sent,true);assert.ok(result[0].bytes<64_000);assert.equal(messages.length,before+1);const direct=s.TemuCatalogNetworkInterceptor.sendEnvelope(s,'TEMU_CATALOG_NETWORK_PRODUCTS',{blob:'x'.repeat(70_000)});assert.equal(direct.sent,false);assert.equal(direct.reason,'PAYLOAD_TOO_LARGE');});

test('50 products are chunked into 20, 20 and 10',()=>{const {s,messages}=bridgeHarness();const products=Array.from({length:50},(_,i)=>({goods_id:String(2000+i),title:`P${i}`}));const result=s.TemuCatalogNetworkInterceptor.sendProducts(s,{products});assert.equal(result.length,3);const rows=messages.filter(x=>x.type==='TEMU_CATALOG_NETWORK_PRODUCTS');assert.deepEqual(rows.map(x=>x.payload.products.length),[20,20,10]);const d=s.TemuCatalogNetworkCache.diagnostics();assert.equal(d.isolated_products_message_received,3);assert.equal(d.isolated_products_received_count,50);assert.equal(d.cache_inserted_goods,50);});

test('40 observed live goods ids cross MAIN to bridge in two accepted chunks',()=>{const {s,messages}=bridgeHarness(),products=liveIdFixture().products;const result=s.TemuCatalogNetworkInterceptor.sendProducts(s,{products});assert.equal(result.length,2);assert.deepEqual(messages.filter(x=>x.type==='TEMU_CATALOG_NETWORK_PRODUCTS').map(x=>x.payload.products.length),[20,20]);const d=s.TemuCatalogNetworkCache.diagnostics(products.map(x=>x.goods_id));assert.equal(d.network_parse_successes,2);assert.equal(d.network_parse_errors,0);assert.equal(d.network_responses_intercepted,2);assert.equal(d.network_unique_goods,40);assert.equal(d.network_enriched_goods,40);assert.equal(s.TemuCatalogNetworkCache.get(products[0].goods_id).goods_id,products[0].goods_id);});

test('40 observed live goods ids cross two actual runtime worlds as 20 plus 20 with zero rejects',()=>{const {main,isolated,messages}=splitWorldHarness(),products=liveIdFixture().products;const result=main.TemuCatalogNetworkInterceptor.sendProducts(main,{products});assert.equal(result.length,2);assert.deepEqual(messages.filter(x=>x.type==='TEMU_CATALOG_NETWORK_PRODUCTS').map(x=>x.payload.products.length),[20,20]);const d=isolated.TemuCatalogNetworkCache.diagnostics(products.map(x=>x.goods_id));assert.equal(d.network_parse_successes,2);assert.equal(d.network_parse_errors,0);assert.equal(d.network_last_parse_error,null);assert.equal(d.network_responses_intercepted,2);assert.equal(d.network_unique_goods,40);assert.equal(d.cache_inserted_goods,40);assert.equal(isolated.TemuCatalogNetworkCache.get(products[0].goods_id).goods_id,products[0].goods_id);});

test('80 live-format rows cross four actual projected messages with zero parser rejects',()=>{const isolatedFiles=['catalog-network-parser.js','catalog-network-cache.js','catalog-product-merger.js','catalog-network-bridge.js'],{main,isolated,messages}=splitWorldHarness({isolatedFiles}),products=liveIdFixture().products;main.TemuCatalogNetworkInterceptor.sendProducts(main,{products});main.TemuCatalogNetworkInterceptor.sendProducts(main,{products});const d=isolated.TemuCatalogNetworkCache.diagnostics(products.map(x=>x.goods_id));assert.deepEqual(messages.filter(x=>x.type==='TEMU_CATALOG_NETWORK_PRODUCTS').map(x=>x.payload.products.length),[20,20,20,20]);assert.equal(d.isolated_products_received_count,80);assert.equal(d.network_product_records,80);assert.equal(d.network_parse_successes,4);assert.equal(d.network_parse_errors,0);assert.equal(d.network_last_parse_error,null);assert.equal(d.network_responses_intercepted,4);assert.equal(d.network_unique_goods,40);assert.equal(d.cache_inserted_goods,40);assert.equal(d.cache_deduped_goods,40);assert.equal(d.parser_stage.parser_records_count,20);assert.equal(d.parser_stage.parser_invalid_identity_count,0);});

test('cache insertion and dedupe counters distinguish repeated goods',()=>{const {s}=bridgeHarness();s.TemuCatalogNetworkInterceptor.sendProducts(s,{products:[{goods_id:'3001',title:'A'}]});s.TemuCatalogNetworkInterceptor.sendProducts(s,{products:[{goods_id:'3001',title:'B'}]});const d=s.TemuCatalogNetworkCache.diagnostics();assert.equal(d.cache_insert_attempts,2);assert.equal(d.cache_inserted_goods,1);assert.equal(d.cache_deduped_goods,1);assert.equal(s.TemuCatalogNetworkCache.get('3001').latestProduct.title,'B');});

test('10 sanitized real fixture products cross MAIN to ISOLATED and enter cache',()=>{const {s}=bridgeHarness();const products=fixture().result.data.goods_list;s.TemuCatalogNetworkInterceptor.sendProducts(s,{products});const d=s.TemuCatalogNetworkCache.diagnostics(products.map(x=>x.goods_id));assert.equal(d.isolated_products_received_count,10);assert.ok(d.network_cache_size>=10);assert.equal(d.network_enriched_goods,10);});

test('fixture enrichment recovers title=icon with network provenance',()=>{const {s}=bridgeHarness();const products=fixture().result.data.goods_list;s.TemuCatalogNetworkInterceptor.sendProducts(s,{products});const merged=s.TemuCatalogProductMerger.mergeDomNetwork({goods_id:'601099602102774',title:'icon',price_amount:10.5},s.TemuCatalogNetworkCache.get('601099602102774'));assert.equal(merged.title,'Y10 Hard Wheat Motorcycle Helmet Headset');assert.equal(merged.field_provenance.title,'network');assert.equal(merged.price_amount,10.5);assert.equal(merged.capture_transport,'NETWORK_ENRICHED');});

test('localized XHR preserves open/send and emits candidate plus minimal products',()=>{const posts=[];const body={result:{data:{goods_list:[{goods_id:'1',title:'A',secret:'drop'},{goods_id:'2',title:'B'}]}}};class FakeXHR{constructor(){this.listeners={};this.status=200;this.responseURL='https://www.temu.com/de-en/api/poppy/v1/opt';this.responseText=JSON.stringify(body);this.responseType='';}open(...args){this.openArgs=args;return 'OPEN_OK';}send(){return 'SEND_OK';}addEventListener(type,fn){this.listeners[type]=fn;}getResponseHeader(){return 'application/json';}}
  const s=sandbox(['catalog-network-endpoints.js','temu-network-interceptor.js'],{location:{href:'https://www.temu.com/de-en/',origin:'https://www.temu.com'},postMessage:m=>posts.push(m),XMLHttpRequest:FakeXHR,crypto:{randomUUID:()=> 'nonce_xhr'}});const xhr=new s.XMLHttpRequest();assert.equal(xhr.open('POST','/de-en/api/poppy/v1/opt'),'OPEN_OK');assert.equal(xhr.send(),'SEND_OK');xhr.listeners.loadend();const candidate=posts.find(x=>x.type==='TEMU_CATALOG_NETWORK_CANDIDATE'),products=posts.find(x=>x.type==='TEMU_CATALOG_NETWORK_PRODUCTS');assert.equal(candidate.source,'temu-network-interceptor');assert.equal(candidate.payload.estimated_product_records,2);assert.equal(products.payload.products.length,2);assert.doesNotMatch(JSON.stringify(products),/secret|drop/);});

test('non-JSON fetch is observed without cloning body',async()=>{let clones=0;const posts=[];const response={url:'https://www.temu.com/de-en/api/poppy/v1/opt',status:200,headers:{get:()=> 'text/html'},clone(){clones++;return {};}};const s=sandbox(['catalog-network-endpoints.js','temu-network-interceptor.js'],{location:{href:'https://www.temu.com/de-en/',origin:'https://www.temu.com'},fetch:async()=>response,postMessage:m=>posts.push(m),crypto:{randomUUID:()=> 'nonce_fetch'}});assert.equal(await s.fetch('/de-en/api/poppy/v1/opt'),response);await new Promise(resolve=>setImmediate(resolve));assert.equal(clones,0);assert.equal(posts.filter(x=>x.type==='TEMU_CATALOG_NETWORK_DIAGNOSTIC').length,1);assert.equal(posts.some(x=>x.type==='TEMU_CATALOG_NETWORK_PRODUCTS'),false);});

test('Poppy opt parser reads the sanitized real-schema fixture without recursion',()=>{const s=sandbox(['catalog-network-endpoints.js','catalog-network-parser.js']);const rows=s.TemuCatalogNetworkParser.parsePoppyOptResponse(fixture());assert.equal(rows.length,10);assert.equal(rows[0].goods_id,'601099602102774');assert.equal(rows[0].title,'Y10 Hard Wheat Motorcycle Helmet Headset');});

test('candidate envelope stores bounded metadata but no formal products',()=>{const {s}=bridgeHarness();const nonce=s.TemuCatalogNetworkInterceptor.getNonce();const message=envelope('TEMU_CATALOG_NETWORK_CANDIDATE',{pathname:'/de-en/api/poppy/v1/opt',status:200,content_type:'application/json',response_size:100,top_level_keys:['result'],goods_id_fields_detected:40,estimated_product_records:40,timestamp:'now'},nonce);assert.equal(invoke(s,message),true);const d=s.TemuCatalogNetworkCache.diagnostics();assert.equal(d.candidate_observations.at(-1).estimated_product_records,40);});

test('diagnostics bound request metadata and count HTTP 429',()=>{const s=sandbox(['catalog-network-cache.js']);const cache=s.TemuCatalogNetworkCache;for(let i=0;i<55;i++)cache.observeRequestMetadata({transport:i%2?'FETCH':'XHR',pathname:`/api/${i}`,status:i===54?429:200,same_origin:true,temu_domain:true});const d=cache.diagnostics();assert.equal(d.recent_requests.length,50);assert.equal(d.total_fetch_seen+d.total_xhr_seen,55);assert.equal(d.rate_limit_observed,1);});

test('bridge rejects malformed product schema and counts rejection',()=>{const {s}=bridgeHarness();const nonce=s.TemuCatalogNetworkInterceptor.getNonce();const bad=envelope('TEMU_CATALOG_NETWORK_PRODUCTS',{endpoint:'/api/poppy/v1/opt',observed_at:'now',products:[{goods_id:'bad',title:'x'}]},nonce);assert.equal(invoke(s,bad),false);assert.equal(s.TemuCatalogNetworkCache.diagnostics().bridge_schema_rejected,1);});

test('bridge canonicalizes localized, absolute, relative-query and trailing-slash opt endpoints',()=>{const s=sandbox(BRIDGE_FILES,{location:{href:'https://www.temu.com/de-en/',origin:'https://www.temu.com',protocol:'https:',hostname:'www.temu.com'},addEventListener:()=>{}});ready(s);for(const [index,endpoint] of ['/de-en/api/poppy/v1/opt/','https://www.temu.com/de-en/api/poppy/v1/opt/?scene=opt','/api/poppy/v1/opt','/de-en/api/poppy/v1/opt/?scene=opt&is_back=1'].entries()){const message=envelope('TEMU_CATALOG_NETWORK_PRODUCTS',{endpoint,observed_at:'now',products:[{goods_id:String(90+index),title:'x'}]});assert.equal(invoke(s,message),true);}assert.equal(s.TemuCatalogNetworkCache.diagnostics().cache_inserted_goods,4);});

test('payload endpoint normalizer supports the observed path-only form and exact safe equivalents',()=>{const s=sandbox(['catalog-network-bridge.js'],{location:{href:'https://www.temu.com/de-en/',origin:'https://www.temu.com',protocol:'https:',hostname:'www.temu.com'},addEventListener:()=>{}}),normalize=s.TemuCatalogNetworkBridge.normalizePayloadEndpoint;assert.equal(normalize('/api/poppy/v1/opt'),'/api/poppy/v1/opt');assert.equal(normalize('/api/poppy/v1/opt/'),'/api/poppy/v1/opt');assert.equal(normalize('https://www.temu.com/api/poppy/v1/opt'),'/api/poppy/v1/opt');assert.equal(normalize('https://www.temu.com/api/poppy/v1/opt?foo=bar'),'/api/poppy/v1/opt');assert.equal(normalize('https://evil.com/api/poppy/v1/opt'),null);});

test('bridge exact endpoint gate rejects suffixes, descendants, other paths and versions',()=>{const s=sandbox(['catalog-network-endpoints.js','catalog-network-cache.js','catalog-network-bridge.js'],{location:{href:'https://www.temu.com/de-en/',origin:'https://www.temu.com',protocol:'https:',hostname:'www.temu.com'},addEventListener:()=>{}});ready(s);for(const [index,endpoint] of ['/api/poppy/v1/opt_fake','/api/poppy/v1/opt/evil','/api/poppy/v1/other','/api/poppy/v2/opt'].entries()){const message=envelope('TEMU_CATALOG_NETWORK_PRODUCTS',{endpoint,observed_at:'now',products:[{goods_id:String(120+index),title:'x'}]});assert.equal(invoke(s,message),false);}const d=s.TemuCatalogNetworkCache.diagnostics();assert.equal(d.cache_inserted_goods,0);assert.equal(d.bridge_last_reject_reason,'endpoint');});

test('bridge still rejects absolute endpoints from a non-Temu host',()=>{const s=sandbox(['catalog-network-endpoints.js','catalog-network-cache.js','catalog-network-bridge.js'],{location:{href:'https://www.temu.com/de-en/',origin:'https://www.temu.com',protocol:'https:',hostname:'www.temu.com'},addEventListener:()=>{}});ready(s);const message=envelope('TEMU_CATALOG_NETWORK_PRODUCTS',{endpoint:'https://evil.example/api/poppy/v1/opt',observed_at:'now',products:[{goods_id:'99',title:'x'}]});assert.equal(invoke(s,message),false);const d=s.TemuCatalogNetworkCache.diagnostics();assert.equal(d.bridge_last_reject_reason,'endpoint');assert.equal(d.cache_inserted_goods,0);});

test('endpoint reject diagnostics retain URL structure while redacting query values',()=>{const s=sandbox(['catalog-network-endpoints.js','catalog-network-cache.js','catalog-network-bridge.js'],{location:{href:'https://www.temu.com/de-en/',origin:'https://www.temu.com',protocol:'https:',hostname:'www.temu.com'},addEventListener:()=>{}});const d=s.TemuCatalogNetworkBridge.diagnosePayloadEndpoint('https://evil.example/api/poppy/v1/opt?token=secret&scene=opt');assert.equal(d.hostname,'evil.example');assert.equal(d.pathname,'/api/poppy/v1/opt');assert.equal(d.search,'?token=<redacted>&scene=<redacted>');assert.equal(d.normalized_endpoint,null);assert.doesNotMatch(JSON.stringify(d),/secret/);});

test('network diagnostics distinguish enrichment and network-only goods',()=>{const s=sandbox(['catalog-network-cache.js']);const cache=s.TemuCatalogNetworkCache;cache.observe({endpoint:'/x',observedAt:'now',products:[{goods_id:'1'},{goods_id:'2'}]});const d=cache.diagnostics(['1','3']);assert.equal(d.network_responses_intercepted,1);assert.equal(d.network_enriched_goods,1);assert.equal(d.network_only_observed,1);});

test('live bridge delegates alias normalization to catalog network parser',()=>{const s=sandbox(BRIDGE_FILES,{location:{href:'https://www.temu.com/de-en/',origin:'https://www.temu.com',protocol:'https:',hostname:'www.temu.com'},addEventListener:()=>{}});ready(s);const message=envelope('TEMU_CATALOG_NETWORK_PRODUCTS',{endpoint:'/api/poppy/v1/opt',observed_at:'now',products:[{goodsId:'401',goodsName:'Alias Title',salePrice:'12.30',soldCount:'45',star:'4.7',commentCount:'6'}]});assert.equal(invoke(s,message),true);const row=s.TemuCatalogNetworkCache.get('401').latestProduct,d=s.TemuCatalogNetworkCache.diagnostics();assert.deepEqual({title:row.title,price_amount:row.price_amount,sales_count:row.sales_count,rating:row.rating,review_count:row.review_count},{title:'Alias Title',price_amount:12.3,sales_count:45,rating:4.7,review_count:6});assert.equal(d.network_parse_successes,1);assert.equal(d.network_parse_errors,0);});

test('bridge isolates parser-unavailable failure without cache insertion',()=>{const files=['catalog-network-endpoints.js','catalog-network-cache.js','catalog-network-bridge.js'];const s=sandbox(files,{location:{href:'https://www.temu.com/de-en/',origin:'https://www.temu.com',protocol:'https:',hostname:'www.temu.com'},addEventListener:()=>{}});ready(s);const message=envelope('TEMU_CATALOG_NETWORK_PRODUCTS',{endpoint:'/api/poppy/v1/opt',observed_at:'now',products:[{goods_id:'402',title:'No parser'}]});assert.equal(invoke(s,message),false);const d=s.TemuCatalogNetworkCache.diagnostics();assert.equal(d.network_parse_errors,1);assert.equal(d.cache_inserted_goods,0);assert.equal(d.bridge_last_reject_reason,'parser_unavailable');});

test('bridge reports parser endpoint-stage rejection instead of goods_id',()=>{const s=sandbox(BRIDGE_FILES,{location:{href:'https://www.temu.com/de-en/',origin:'https://www.temu.com',protocol:'https:',hostname:'www.temu.com'},addEventListener:()=>{}});ready(s);s.TemuCatalogNetworkParser={analyzeProductRecords:()=>({records:[],invalid:[],status:'endpoint_rejected',stage:'endpoint_gate',diagnostics:{parser_stage:'endpoint_gate',parser_status:'endpoint_rejected',parser_input_count:1,parser_endpoint_raw:'/api/poppy/v1/opt',parser_endpoint_type:'string',parser_base:'https://www.temu.com/de-en/',parser_endpoint_normalized:'/api/poppy/v1/opt',parser_endpoint_allowed:false,parser_endpoint_helper_available:false,parser_endpoint_validation_source:'none',parser_collect_attempted:false,parser_records_count:0,parser_invalid_identity_count:0}})};assert.equal(invoke(s,envelope('TEMU_CATALOG_NETWORK_PRODUCTS',{endpoint:'/api/poppy/v1/opt',observed_at:'now',products:[{goods_id:'601099602102774'}]})),false);const d=s.TemuCatalogNetworkCache.diagnostics();assert.equal(d.bridge_last_reject_reason,'parser_endpoint_not_allowed');assert.equal(d.network_last_parse_error.reason,'endpoint_not_allowed');assert.equal(d.network_last_parse_error.stage,'endpoint_gate');assert.equal(d.parser_stage.parser_collect_attempted,false);});

test('bridge reports collection-stage empty result instead of goods_id',()=>{const s=sandbox(BRIDGE_FILES,{location:{href:'https://www.temu.com/de-en/',origin:'https://www.temu.com',protocol:'https:',hostname:'www.temu.com'},addEventListener:()=>{}});ready(s);s.TemuCatalogNetworkParser={analyzeProductRecords:()=>({records:[],invalid:[],status:'collection_empty',stage:'product_collection',diagnostics:{parser_stage:'product_collection',parser_status:'collection_empty',parser_input_count:1,parser_endpoint_raw:'/api/poppy/v1/opt',parser_endpoint_type:'string',parser_base:'https://www.temu.com/de-en/',parser_endpoint_normalized:'/api/poppy/v1/opt',parser_endpoint_allowed:true,parser_endpoint_helper_available:true,parser_endpoint_validation_source:'helper',parser_collect_attempted:true,parser_records_count:0,parser_invalid_identity_count:0}})};assert.equal(invoke(s,envelope('TEMU_CATALOG_NETWORK_PRODUCTS',{endpoint:'/api/poppy/v1/opt',observed_at:'now',products:[{goods_id:'601099602102774'}]})),false);const d=s.TemuCatalogNetworkCache.diagnostics();assert.equal(d.bridge_last_reject_reason,'parser_collection_empty');assert.equal(d.network_last_parse_error.reason,'parser_collection_empty');assert.equal(d.network_last_parse_error.stage,'product_collection');assert.equal(d.parser_stage.parser_collect_attempted,true);});

test('bridge isolates an invalid identity while caching valid rows with safe diagnostics',()=>{const s=sandbox(BRIDGE_FILES,{location:{href:'https://www.temu.com/de-en/',origin:'https://www.temu.com',protocol:'https:',hostname:'www.temu.com'},addEventListener:()=>{}});ready(s);const message=envelope('TEMU_CATALOG_NETWORK_PRODUCTS',{endpoint:'/api/poppy/v1/opt',observed_at:'now',products:[{goods_id:'601099602102774'},{goods_id:'12345678901234567'}]});assert.equal(invoke(s,message),true);const d=s.TemuCatalogNetworkCache.diagnostics(),invalid=d.network_last_parse_error.invalid[0];assert.equal(d.network_parse_successes,1);assert.equal(d.network_parse_errors,1);assert.equal(d.cache_inserted_goods,1);assert.equal(d.network_last_parse_error.reason,'invalid_goods_id');assert.equal(d.network_last_parse_error.stage,'identity_normalization');assert.equal(d.parser_stage.parser_invalid_identity_count,1);assert.equal(JSON.stringify(invalid),JSON.stringify({index:1,type:'string',length:17,digit_only:true,prefix:'1234',suffix:'4567'}));});

test('goods-id mismatch falls back to DOM and records merge conflict',()=>{const s=sandbox(['catalog-network-cache.js','catalog-product-merger.js']);const merged=s.TemuCatalogProductMerger.mergeDomNetwork({goods_id:'501',title:'DOM title'},{latestProduct:{goods_id:'502',title:'Network title'}});assert.equal(merged.title,'DOM title');assert.equal(merged.capture_transport,'DOM');assert.equal(s.TemuCatalogNetworkCache.diagnostics().network_merge_conflicts,1);});
