import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {migrateSourcingDatabase} from '../../src/modules/sourcing/sourcing-db.mjs';import {openDatabase} from '../../src/db/client.mjs';
import {createTemuMarketEvidenceRepository} from '../../src/db/repositories/temu-market-evidence-repository.mjs';

function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'evidence-repo-')),dbPath=path.join(dir,'db.sqlite');migrateSourcingDatabase({databasePath:dbPath});const db=openDatabase(dbPath,{allowRunnerWrite:true});db.prepare(`INSERT INTO sourcing_runs(run_id,git_commit_sha,machine_role,machine_name,started_at,status,input_count,target_count,input_manifest_sha256,created_at,updated_at) VALUES('r','g','1688_RUNNER','m','2026-01-01','COMPLETED',2,2,'h','2026-01-01','2026-01-01')`).run();for(const id of ['1','2'])db.prepare(`INSERT INTO sourcing_run_items(run_id,temu_goods_id,temu_title,temu_image_path,status,updated_at) VALUES('r',?,?,?,'COMPLETED','2026-01-01')`).run(id,`goods ${id}`,`${id}.jpg`);return{dir,db,repo:createTemuMarketEvidenceRepository(db,{now:()=>new Date('2026-09-03T00:00:00Z')})};}

test('owns sessions explicitly and permits one writable session per review goods',()=>{const f=fixture();try{const made=f.repo.createSession({reviewRunId:'r',anchorTemuGoodsId:'1',query:'girls dress',requestId:'create-1'});assert.equal(made.session.status,'CREATED');assert.ok(made.bindToken);assert.throws(()=>f.repo.createSession({reviewRunId:'r',anchorTemuGoodsId:'1',query:'other',requestId:'create-2'}),e=>e.code==='EVIDENCE_SESSION_ALREADY_WRITABLE');assert.throws(()=>f.repo.getSession('r','2',made.session.session_id),e=>e.code==='EVIDENCE_SESSION_CONTEXT_MISMATCH');const closed=f.repo.closeSession({reviewRunId:'r',anchorTemuGoodsId:'1',sessionId:made.session.session_id,expectedRevision:0,requestId:'close-1'});assert.equal(closed.status,'CLOSED');assert.equal(f.repo.createSession({reviewRunId:'r',anchorTemuGoodsId:'1',query:'other',requestId:'create-2'}).session.status,'CREATED');}finally{f.db.close();fs.rmSync(f.dir,{recursive:true,force:true});}});

test('consumes one-time bind token and enforces optimistic revisions',()=>{const f=fixture();try{const made=f.repo.createSession({reviewRunId:'r',anchorTemuGoodsId:'1',query:'girls dress',requestId:'create'});const bound=f.repo.consumeBindToken({bindToken:made.bindToken,tabIdentityHash:'tab',contextHash:'ctx',pageUrl:'https://www.temu.com/search_result.html?search_key=girls+dress',query:'girls dress',requestId:'bind'});assert.equal(bound.status,'BOUND');assert.equal(bound.revision,1);assert.throws(()=>f.repo.consumeBindToken({bindToken:made.bindToken,tabIdentityHash:'tab',contextHash:'ctx',pageUrl:'x',query:'girls dress',requestId:'bind2'}),e=>e.code==='EVIDENCE_BIND_TOKEN_INVALID');assert.throws(()=>f.repo.closeSession({reviewRunId:'r',anchorTemuGoodsId:'1',sessionId:made.session.session_id,expectedRevision:0,requestId:'close'}),e=>e.code==='EVIDENCE_SESSION_REVISION_CONFLICT');}finally{f.db.close();fs.rmSync(f.dir,{recursive:true,force:true});}});

test('consumed token rehydrates only the identical bound tab and context with zero writes',()=>{const f=fixture();try{const made=f.repo.createSession({reviewRunId:'r',anchorTemuGoodsId:'1',query:'girls dress',requestId:'create'}),input={bindToken:made.bindToken,tabIdentityHash:'tab',contextHash:'ctx',pageUrl:'https://www.temu.com/search_result.html?search_key=girls+dress',query:'girls dress'};const bound=f.repo.consumeBindToken({...input,requestId:'bind'}),before={changes:f.db.totalChanges,requests:f.db.prepare('SELECT COUNT(*) n FROM temu_market_evidence_requests').get().n,revision:bound.revision};const hydrated=f.repo.consumeBindToken({...input,requestId:'reconnect'});assert.equal(hydrated.session_id,bound.session_id);assert.equal(hydrated.revision,before.revision);assert.deepEqual({changes:f.db.totalChanges,requests:f.db.prepare('SELECT COUNT(*) n FROM temu_market_evidence_requests').get().n},{changes:before.changes,requests:before.requests});}finally{f.db.close();fs.rmSync(f.dir,{recursive:true,force:true});}});
