import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {migrateSourcingDatabase} from '../../src/modules/sourcing/sourcing-db.mjs';import {openDatabase} from '../../src/db/client.mjs';
import {createTemuMarketEvidenceRepository} from '../../src/db/repositories/temu-market-evidence-repository.mjs';

function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'evidence-repo-')),dbPath=path.join(dir,'db.sqlite');migrateSourcingDatabase({databasePath:dbPath});const db=openDatabase(dbPath,{allowRunnerWrite:true});db.prepare(`INSERT INTO sourcing_runs(run_id,git_commit_sha,machine_role,machine_name,started_at,status,input_count,target_count,input_manifest_sha256,created_at,updated_at) VALUES('r','g','1688_RUNNER','m','2026-01-01','COMPLETED',2,2,'h','2026-01-01','2026-01-01')`).run();for(const id of ['1','2'])db.prepare(`INSERT INTO sourcing_run_items(run_id,temu_goods_id,temu_title,temu_image_path,status,updated_at) VALUES('r',?,?,?,'COMPLETED','2026-01-01')`).run(id,`goods ${id}`,`${id}.jpg`);return{dir,db,repo:createTemuMarketEvidenceRepository(db,{now:()=>new Date('2026-09-03T00:00:00Z')})};}

test('owns sessions explicitly and permits one writable session per review goods',()=>{const f=fixture();try{const made=f.repo.createSession({reviewRunId:'r',anchorTemuGoodsId:'1',query:'girls dress',requestId:'create-1'});assert.equal(made.session.status,'CREATED');assert.ok(made.bindToken);assert.throws(()=>f.repo.createSession({reviewRunId:'r',anchorTemuGoodsId:'1',query:'other',requestId:'create-2'}),e=>e.code==='EVIDENCE_SESSION_ALREADY_WRITABLE');assert.throws(()=>f.repo.getSession('r','2',made.session.session_id),e=>e.code==='EVIDENCE_SESSION_CONTEXT_MISMATCH');const closed=f.repo.closeSession({reviewRunId:'r',anchorTemuGoodsId:'1',sessionId:made.session.session_id,expectedRevision:0,requestId:'close-1'});assert.equal(closed.status,'CLOSED');assert.equal(f.repo.createSession({reviewRunId:'r',anchorTemuGoodsId:'1',query:'other',requestId:'create-2'}).session.status,'CREATED');}finally{f.db.close();fs.rmSync(f.dir,{recursive:true,force:true});}});

test('consumes one-time bind token and enforces optimistic revisions',()=>{const f=fixture();try{const made=f.repo.createSession({reviewRunId:'r',anchorTemuGoodsId:'1',query:'girls dress',requestId:'create'});const bound=f.repo.consumeBindToken({bindToken:made.bindToken,tabIdentityHash:'tab',contextHash:'ctx',pageUrl:'https://www.temu.com/search_result.html?search_key=girls+dress',query:'girls dress',requestId:'bind'});assert.equal(bound.status,'BOUND');assert.equal(bound.revision,1);assert.throws(()=>f.repo.consumeBindToken({bindToken:made.bindToken,tabIdentityHash:'tab',contextHash:'ctx',pageUrl:'x',query:'girls dress',requestId:'bind2'}),e=>e.code==='EVIDENCE_BIND_TOKEN_INVALID');assert.throws(()=>f.repo.closeSession({reviewRunId:'r',anchorTemuGoodsId:'1',sessionId:made.session.session_id,expectedRevision:0,requestId:'close'}),e=>e.code==='EVIDENCE_SESSION_REVISION_CONFLICT');}finally{f.db.close();fs.rmSync(f.dir,{recursive:true,force:true});}});

test('consumed token rehydrates only the identical bound tab and context with zero writes',()=>{const f=fixture();try{const made=f.repo.createSession({reviewRunId:'r',anchorTemuGoodsId:'1',query:'girls dress',requestId:'create'}),input={bindToken:made.bindToken,tabIdentityHash:'tab',contextHash:'ctx',pageUrl:'https://www.temu.com/search_result.html?search_key=girls+dress',query:'girls dress'};const bound=f.repo.consumeBindToken({...input,requestId:'bind'});f.db.prepare("UPDATE temu_market_evidence_sessions SET bind_token_expires_at='2026-01-01T00:00:00.000Z' WHERE session_id=?").run(bound.session_id);const before={changes:f.db.totalChanges,requests:f.db.prepare('SELECT COUNT(*) n FROM temu_market_evidence_requests').get().n,revision:bound.revision},hydrated=f.repo.consumeBindToken({...input,requestId:'reconnect'});assert.equal(hydrated.session_id,bound.session_id);assert.equal(hydrated.revision,before.revision);assert.deepEqual({changes:f.db.totalChanges,requests:f.db.prepare('SELECT COUNT(*) n FROM temu_market_evidence_requests').get().n},{changes:before.changes,requests:before.requests});}finally{f.db.close();fs.rmSync(f.dir,{recursive:true,force:true});}});

test('operator reissues one token for the explicit BOUND session and invalidates its old binding atomically',()=>{const f=fixture();try{const made=f.repo.createSession({reviewRunId:'r',anchorTemuGoodsId:'1',query:'girls dress',requestId:'create'}),bound=f.repo.consumeBindToken({bindToken:made.bindToken,tabIdentityHash:'tab',contextHash:'ctx',pageUrl:'page',query:'girls dress',requestId:'bind'}),input={reviewRunId:'r',anchorTemuGoodsId:'1',sessionId:bound.session_id,expectedRevision:1,requestId:'reissue'};const result=f.repo.reissueBindToken(input),row=f.db.prepare('SELECT * FROM temu_market_evidence_sessions WHERE session_id=?').get(bound.session_id);assert.ok(result.bindToken);assert.notEqual(result.bindToken,made.bindToken);assert.equal(result.session.status,'BOUND');assert.equal(result.session.revision,2);assert.equal(row.bind_token_consumed_at,null);assert.equal(row.bound_tab_identity_hash,null);assert.equal(f.repo.reissueBindToken(input).bindToken,result.bindToken);assert.throws(()=>f.repo.consumeBindToken({bindToken:made.bindToken,tabIdentityHash:'tab',contextHash:'ctx',pageUrl:'page',query:'girls dress',requestId:'old'}),e=>e.code==='EVIDENCE_BIND_TOKEN_INVALID');const rebound=f.repo.consumeBindToken({bindToken:result.bindToken,tabIdentityHash:'tab',contextHash:'ctx',pageUrl:'page',query:'girls dress',requestId:'new'});assert.equal(rebound.status,'BOUND');assert.equal(rebound.revision,3);}finally{f.db.close();fs.rmSync(f.dir,{recursive:true,force:true});}});

test('reissue wrong ownership revision or lifecycle performs zero writes',()=>{const f=fixture();try{const made=f.repo.createSession({reviewRunId:'r',anchorTemuGoodsId:'1',query:'girls dress',requestId:'create'}),before=f.db.totalChanges;assert.throws(()=>f.repo.reissueBindToken({reviewRunId:'r',anchorTemuGoodsId:'1',sessionId:made.session.session_id,expectedRevision:0,requestId:'bad-status'}),e=>e.code==='EVIDENCE_SESSION_PHASE_ORDER_INVALID');assert.equal(f.db.totalChanges,before);const bound=f.repo.consumeBindToken({bindToken:made.bindToken,tabIdentityHash:'tab',contextHash:'ctx',pageUrl:'page',query:'girls dress',requestId:'bind'}),afterBind=f.db.totalChanges;assert.throws(()=>f.repo.reissueBindToken({reviewRunId:'r',anchorTemuGoodsId:'1',sessionId:bound.session_id,expectedRevision:0,requestId:'bad-revision'}),e=>e.code==='EVIDENCE_SESSION_REVISION_CONFLICT');assert.throws(()=>f.repo.reissueBindToken({reviewRunId:'r',anchorTemuGoodsId:'2',sessionId:bound.session_id,expectedRevision:1,requestId:'bad-goods'}),e=>e.code==='EVIDENCE_SESSION_CONTEXT_MISMATCH');assert.equal(f.db.totalChanges,afterBind);}finally{f.db.close();fs.rmSync(f.dir,{recursive:true,force:true});}});

test('Temu-truncated effective query requires an explicit second confirmation with zero first-attempt writes',()=>{const f=fixture();try{const requested='scooter with this petrol inline fuel gas filter',effective='scooter with this petrol inline',made=f.repo.createSession({reviewRunId:'r',anchorTemuGoodsId:'1',query:requested,requestId:'create'}),input={bindToken:made.bindToken,tabIdentityHash:'tab',contextHash:`www.temu.com|/search_result.html|${effective}`,pageUrl:`https://www.temu.com/search_result.html?search_key=${encodeURIComponent(effective)}`,query:effective,requestId:'bind'},before={changes:f.db.totalChanges,requests:f.db.prepare('SELECT COUNT(*) n FROM temu_market_evidence_requests').get().n};assert.throws(()=>f.repo.consumeBindToken(input),e=>e.code==='EVIDENCE_EFFECTIVE_QUERY_CONFIRMATION_REQUIRED');assert.deepEqual({changes:f.db.totalChanges,requests:f.db.prepare('SELECT COUNT(*) n FROM temu_market_evidence_requests').get().n},before);const bound=f.repo.consumeBindToken({...input,confirmEffectiveQuery:true});assert.equal(bound.query,requested);assert.equal(bound.effective_query,effective);assert.equal(bound.status,'BOUND');assert.equal(bound.revision,1);}finally{f.db.close();fs.rmSync(f.dir,{recursive:true,force:true});}});

test('confirmed effective query becomes the strict phase query and unrelated query remains blocked',()=>{const f=fixture();try{const requested='scooter with this petrol inline fuel gas filter',effective='scooter with this petrol inline',made=f.repo.createSession({reviewRunId:'r',anchorTemuGoodsId:'1',query:requested,requestId:'create'}),pageUrl=`https://www.temu.com/search_result.html?search_key=${encodeURIComponent(effective)}`,bound=f.repo.consumeBindToken({bindToken:made.bindToken,tabIdentityHash:'tab',contextHash:'ctx',pageUrl,query:effective,confirmEffectiveQuery:true,requestId:'bind'});assert.equal(f.repo.requireWritable({reviewRunId:'r',anchorTemuGoodsId:'1',sessionId:bound.session_id,expectedRevision:1,tabIdentityHash:'tab',query:effective},['BOUND']).effective_query,effective);assert.throws(()=>f.repo.requireWritable({reviewRunId:'r',anchorTemuGoodsId:'1',sessionId:bound.session_id,expectedRevision:1,tabIdentityHash:'tab',query:'unrelated'},['BOUND']),e=>e.code==='EVIDENCE_SESSION_CONTEXT_MISMATCH');}finally{f.db.close();fs.rmSync(f.dir,{recursive:true,force:true});}});
